#lang sicp
;; SICP 第二版 §1.3.3–1.3.4，1.35 / 1.46。
;; average-damp、deriv、Newton 组织据教材改写；失败上限与边界为补充。
(#%require (only racket/base with-handlers exn:fail?))
(define tolerance 1e-12)
(define (finite-real? x)
  (and (real? x) (= x x) (< (abs x) +inf.0)))
(define (require-finite x)
  (if (not (finite-real? x)) (error "Expected finite real iterate" x) #t))
(define (close? a b)
  (<= (abs (- a b)) (* tolerance (max 1.0 (abs a) (abs b)))))
(define (relative-close? a b)
  (or (= a b)
      (and (> (max (abs a) (abs b)) 0)
           (<= (/ (abs (- a b)) (max (abs a) (abs b))) tolerance))))

;; 1.46：单参数 good-enough?，先判断当前猜测，必要时才 improve。
(define (iterative-improve good-enough? improve)
  (lambda (first-guess)
    (define (iter guess remaining)
      (require-finite guess)
      (cond ((good-enough? guess) guess)
            ((= remaining 0) (error "Iteration limit: no convergence" guess))
            (else (iter (improve guess) (- remaining 1)))))
    (iter first-guess 4096)))

(define (fixed-point f first-guess)
  (define (good-enough? guess)
    (let ((next (f guess)))
      (require-finite next)
      (close? guess next)))
  ;; 返回最后一次 next，与教材 fixed-point 的接口一致。
  (f ((iterative-improve good-enough? f) first-guess)))

(define (sqrt-improved input)
  (require-finite input)
  (define x (exact->inexact input))
  (define (improve guess) (+ (/ guess 2.0) (/ (/ x guess) 2.0)))
  (cond ((< input 0) (error "Real square root needs x >= 0" input))
        ((or (not (finite-real? x)) (and (not (= input 0)) (= x 0)))
         (error "Input outside inexact range" input))
        ((= x 0) 0.0)
        (else ((iterative-improve
                (lambda (guess) (relative-close? guess (improve guess)))
                improve)
               1.0))))

(define (average-damp f)
  (lambda (x) (+ (/ x 2.0) (/ (f x) 2.0))))
(define (compose f g) (lambda (x) (f (g x))))
(define dx 1e-5)
(define (deriv g)
  (lambda (x) (/ (- (g (+ x dx)) (g x)) dx)))
(define (newton-transform g)
  (let ((dg (deriv g)))
    (lambda (x)
      (let ((value (g x)) (slope (dg x)))
        (require-finite value) (require-finite slope)
        (cond ((= value 0) x)
              ((= slope 0) (error "Zero numerical derivative" x))
              (else (- x (/ value slope))))))))
(define (fixed-point-of-transform g transform guess)
  (fixed-point (transform g) guess))
(define (newtons-method g guess)
  (fixed-point-of-transform g newton-transform guess))

;; 连续性是调用者保证的数学前提；程序能检查端点符号，不能检查连续性。
(define (half-interval-method f a b)
  (require-finite a) (require-finite b)
  (define (value x)
    (let ((y (f x))) (require-finite y) y))
  (define (search negative positive remaining)
    (let ((mid (+ (/ negative 2.0) (/ positive 2.0))))
      (cond ((< (abs (- positive negative)) 1e-10) mid)
            ((or (= remaining 0) (= mid negative) (= mid positive))
             (error "Bisection cannot refine interval" negative positive))
            (else (let ((v (value mid)))
                    (cond ((= v 0) mid)
                          ((< v 0) (search mid positive (- remaining 1)))
                          (else (search negative mid (- remaining 1)))))))))
  (let ((fa (value a)) (fb (value b)))
    (cond ((= fa 0) a)
          ((= fb 0) b)
          ((and (< fa 0) (> fb 0)) (search a b 4096))
          ((and (> fa 0) (< fb 0)) (search b a 4096))
          (else (error "Endpoints must bracket a zero" a b)))))

;; 1.35：实际通过不动点迭代计算，不用黄金比例公式代替算法。
(define (golden-ratio) (fixed-point (lambda (x) (+ 1 (/ 1 x))) 1.0))
(define (check label ok)
  (if (not ok) (error "Check failed" label) #t))
(define (check-near label actual expected)
  (check label (< (abs (- actual expected)) 1e-8)))
(define (raises? thunk)
  (with-handlers ((exn:fail? (lambda (e) #t))) (thunk) #f))
(define (self-check)
  (let ((phi (golden-ratio)))
    (check-near 'golden-ratio phi (/ (+ 1 (sqrt 5)) 2))
    (check-near 'golden-equation (* phi phi) (+ phi 1))
    (display "phi = ") (display phi) (newline))
  (check-near 'cosine-fixed-point (fixed-point cos 1.0) 0.7390851332151607)
  (check-near 'fixed-zero (fixed-point (lambda (x) (/ x 2)) 1.0) 0)
  (check-near 'sqrt (sqrt-improved 2) (sqrt 2))
  (check 'sqrt-zero (= (sqrt-improved 0) 0))
  (for-each
   (lambda (row)
     (check row (< (/ (abs (- (sqrt-improved (car row)) (cadr row)))
                     (cadr row)) 1e-10)))
   '((1e-300 1e-150) (1e300 1e150)))
  (check-near 'damped-square ((average-damp (lambda (x) (* x x))) 10) 55)
  (check-near 'damped-root
              (fixed-point-of-transform (lambda (y) (/ 2 y)) average-damp 1.0)
              (sqrt 2))
  (check 'compose (= ((compose (lambda (x) (* x x)) inc) 6) 49))
  (check 'derivative (< (abs (- ((deriv (lambda (x) (* x x x))) 5) 75)) 0.001))
  (check-near 'newton-root
              (newtons-method (lambda (y) (- (* y y) 2)) 1.0) (sqrt 2))
  (check-near 'bisection (half-interval-method sin 2.0 4.0) 3.141592653589793)
  (check-near 'reversed-bracket (half-interval-method sin 4.0 2.0) 3.141592653589793)
  (check 'endpoint (= (half-interval-method (lambda (x) x) 0 2) 0))
  (check 'initial-good
         (= ((iterative-improve (lambda (x) (= x 7))
                                (lambda (x) (error "Must not improve"))) 7) 7))
  (check 'negative-root (raises? (lambda () (sqrt-improved -1))))
  (check 'bad-bracket
         (raises? (lambda () (half-interval-method (lambda (x) (+ (* x x) 1)) -1 1))))
  (check 'oscillation
         (raises? (lambda () (fixed-point (lambda (x) (- x)) 1.0))))
  (check 'nonfinite
         (raises? (lambda () (fixed-point (lambda (x) +inf.0) 1.0))))
  (check 'zero-slope
         (raises? (lambda () (newtons-method (lambda (x) 1) 0.0))))
  (display "01.06: all checks passed") (newline))
(self-check)
