#lang sicp
;; SICP 第二版 §1.1.7–1.1.8，1.6 / 1.7 / 1.8。
;; 牛顿更新与内部定义据教材改写；相对终止、零与错误处理为课程补充。
(#%require (only racket/base with-handlers exn:fail?))

;; 1.6：只是选择已求值的参数；不运行原题的无限 sqrt-iter。
(define (new-if predicate then-clause else-clause)
  (cond (predicate then-clause) (else else-clause)))

(define tolerance 1e-12)
(define (finite-real? x)
  (and (real? x) (= x x) (< (abs x) +inf.0)))
(define (checked-inexact x)
  (if (not (finite-real? x))
      (error "Expected a finite real" x)
      (let ((v (exact->inexact x)))
        (if (or (not (finite-real? v)) (and (not (= x 0)) (= v 0)))
            (error "Input outside inexact range" x)
            v))))
(define (relatively-close? old next)
  ;; 除以尺度，避免 tolerance * scale 在极小值处下溢。
  (or (= old next)
      (let ((scale (max (abs old) (abs next))))
        (and (> scale 0)
             (<= (/ (abs (- next old)) scale) tolerance)))))

;; 1.7：用户只调用 sqrt-relative，辅助过程通过词法作用域读取 x。
(define (sqrt-relative input)
  (define x (checked-inexact input))
  (define (improve guess)
    (+ (/ guess 2.0) (/ (/ x guess) 2.0)))
  (define (iter guess remaining)
    (if (= remaining 0)
        (error "Square root did not converge" x)
        (let ((next (improve guess)))
          (cond ((not (finite-real? next)) (error "Nonfinite square-root step"))
                ((relatively-close? guess next) next)
                (else (iter next (- remaining 1)))))))
  (cond ((< x 0) (error "Real square root needs x >= 0" input))
        ((= x 0) 0.0)
        (else (iter 1.0 4096))))

;; 保留原终止条件作有限观察；stalled 不是原算法的成功出口。
;; 返回 (状态 猜测 更新次数 平方残差)，不用真的执行无限循环。
(define (legacy-sqrt-observe x)
  (define (iter guess steps)
    (let ((residual (abs (- (* guess guess) x))))
      (if (< residual 0.001)
          (list 'accepted guess steps residual)
          (let ((next (/ (+ guess (/ x guess)) 2.0)))
            (cond ((= guess next) (list 'stalled guess steps residual))
                  ((= steps 4096) (list 'limit guess steps residual))
                  (else (iter next (+ steps 1))))))))
  (iter 1.0 0))

;; 1.8：(x/y^2 + 2y)/3；按同号猜测处理负立方根。
(define (cube-root input)
  (define x (checked-inexact input))
  (define (improve guess)
    ;; 分次相除避免 y*y 溢出；分配除以 3 避免 2*y 溢出。
    (+ (* (/ 2.0 3.0) guess) (/ (/ (/ x guess) guess) 3.0)))
  (define (iter guess remaining)
    (if (= remaining 0)
        (error "Cube root did not converge" x)
        (let ((next (improve guess)))
          (cond ((not (finite-real? next)) (error "Nonfinite cube-root step"))
                ((relatively-close? guess next) next)
                (else (iter next (- remaining 1)))))))
  (cond ((= x 0) 0.0)
        ((< x 0) (iter -1.0 4096))
        (else (iter 1.0 4096))))

(define (check label ok)
  (if (not ok) (error "Check failed" label) #t))
(define (check-relative label actual expected)
  (check label (if (= expected 0)
                   (= actual 0)
                   (< (/ (abs (- actual expected)) (abs expected)) 1e-10))))
(define (raises? thunk)
  (with-handlers ((exn:fail? (lambda (e) #t))) (thunk) #f))

(define (self-check)
  (check 'new-if-value (= (new-if (= 2 3) 0 5) 5))
  (check 'new-if-eager (raises? (lambda () (new-if #t 0 (/ 1 0)))))
  (check 'if-short-circuit (= (if #t 0 (/ 1 0)) 0))
  (for-each (lambda (row)
              (check-relative row (sqrt-relative (car row)) (cadr row)))
            '((0 0) (1 1) (4 2) (2 1.4142135623730951)
              (1/4 1/2) (1e-24 1e-12) (1e-300 1e-150)
              (1e100 1e50) (1e300 1e150)))
  (for-each (lambda (row)
              (check-relative row (cube-root (car row)) (cadr row)))
            '((0 0) (1 1) (8 2) (-8 -2) (27 3) (-1/8 -1/2)
              (1e-300 1e-100) (-1e-300 -1e-100)
              (1e300 1e100) (-1e300 -1e100)))
  (let ((small (legacy-sqrt-observe 1e-12))
        (large (legacy-sqrt-observe 1e100)))
    (check 'tiny-accepted (eq? (car small) 'accepted))
    (check 'tiny-inaccurate (> (/ (cadr small) 1e-6) 1000))
    (check 'large-stalled (eq? (car large) 'stalled))
    (check 'large-residual (> (cadddr large) 0.001))
    (display "legacy tiny: ") (display small) (newline)
    (display "legacy large: ") (display large) (newline))
  (check 'negative-square-root (raises? (lambda () (sqrt-relative -1))))
  (check 'infinity (raises? (lambda () (sqrt-relative +inf.0))))
  (check 'nan (raises? (lambda () (cube-root +nan.0))))
  (check 'complex (raises? (lambda () (cube-root 1+2i))))
  (check 'conversion-overflow
         (raises? (lambda () (sqrt-relative (expt 10 1000)))))
  (display "01.02: all checks passed") (newline))
(self-check)
