#lang sicp
(#%require (only racket/base with-handlers exn:fail?))
;; SICP §2.1.4, exact reciprocals retain exact bounds in these examples.
(define (finite-real? x) (and (real? x) (< -inf.0 x +inf.0)))
(define (make-interval lo hi)
  (if (and (finite-real? lo) (finite-real? hi) (<= lo hi))
      (cons lo hi) (error "invalid ordered finite interval" lo hi)))
(define lower-bound car)
(define upper-bound cdr)
(define (add-interval x y)
  (make-interval (+ (lower-bound x) (lower-bound y))
                 (+ (upper-bound x) (upper-bound y))))
(define (sub-interval x y)
  (make-interval (- (lower-bound x) (upper-bound y))
                 (- (upper-bound x) (lower-bound y))))
(define (mul-interval x y)
  (let ((a (* (lower-bound x) (lower-bound y)))
        (b (* (lower-bound x) (upper-bound y)))
        (c (* (upper-bound x) (lower-bound y)))
        (d (* (upper-bound x) (upper-bound y))))
    (make-interval (min a b c d) (max a b c d))))
(define (div-interval x y)
  (if (<= (lower-bound y) 0 (upper-bound y))
      (error "divisor interval contains zero" y)
      (mul-interval x (make-interval (/ 1 (upper-bound y))
                                     (/ 1 (lower-bound y))))))
(define (center x) (/ (+ (lower-bound x) (upper-bound x)) 2))
(define (width x) (/ (- (upper-bound x) (lower-bound x)) 2))
(define (make-center-percent c p)
  (if (not (and (finite-real? c) (finite-real? p) (>= p 0)))
      (error "invalid center/tolerance" c p)
      (let ((w (* (abs c) (/ p 100)))) (make-interval (- c w) (+ c w)))))
(define (percent x)
  (if (= (center x) 0) (error "relative tolerance undefined at zero center")
      (* 100 (/ (width x) (abs (center x))))))
(define (par1 a b) (div-interval (mul-interval a b) (add-interval a b)))
(define (par2 a b)
  (let ((one (make-interval 1 1)))
    (div-interval one (add-interval (div-interval one a) (div-interval one b)))))
(define (check label actual expected)
  (if (not (equal? actual expected)) (error "check failed" label actual expected)))
(define (check-error label thunk)
  (check label (with-handlers ((exn:fail? (lambda (e) #t))) (thunk) #f) #t))
(define (show label i)
  (display label) (display ": bounds=") (display i)
  (display " center=") (display (exact->inexact (center i)))
  (display " percent=") (display (exact->inexact (percent i))) (newline))
(define (self-check)
  (let ((a (make-center-percent 100 1)) (b (make-center-percent 200 1)))
    (check 'a/a (div-interval a a) (make-interval 99/101 101/99))
    (check 'a/b (div-interval a b) (make-interval 99/202 101/198))
    (check 'par1 (par1 a b) (make-interval 6534/101 20402/297))
    (check 'par2 (par2 a b) (make-interval 66 202/3))
    (check 'tighter (< (width (par2 a b)) (width (par1 a b))) #t)
    (show 'A/A (div-interval a a)) (show 'A/B (div-interval a b))
    (show 'par1 (par1 a b)) (show 'par2 (par2 a b)))
  (check 'negative-divisor (div-interval (make-interval 2 4) (make-interval -2 -1))
         (make-interval -4 -1))
  (check 'mixed-product (mul-interval (make-interval -2 3) (make-interval -4 5))
         (make-interval -12 15))
  (check 'sub (sub-interval (make-interval 2 3) (make-interval 1 4))
         (make-interval -2 2))
  (check 'point (div-interval (make-interval 2 2) (make-interval 2 2)) (make-interval 1 1))
  (for-each (lambda (i) (check-error i (lambda () (div-interval (make-interval 1 2) i))))
            (list (make-interval -1 1) (make-interval 0 1)
                  (make-interval -1 0) (make-interval 0 0)))
  (check-error 'reverse (lambda () (make-interval 2 1)))
  (check-error 'nan (lambda () (make-interval +nan.0 1)))
  (check-error 'infinite (lambda () (make-interval 0 +inf.0)))
  (check-error 'negative-percent (lambda () (make-center-percent 3 -1)))
  (check-error 'zero-center (lambda () (percent (make-interval -1 1))))
  (check 'negative-center (percent (make-center-percent -10 5)) 5)
  (display "02.02: all checks passed") (newline))
(self-check)
