#lang sicp
(#%provide (all-defined))
(#%require (only racket/base with-handlers exn:fail?))

;; SICP §5.2 instruction language; vector PC is an adaptation, not a CPU emulator.
(define (check label actual expected)
  (if (not (equal? actual expected)) (error "check failed" label actual expected) 'ok))
(define (check-error label thunk)
  (check label (with-handlers ((exn:fail? (lambda (e) 'caught))) (thunk) 'not-raised) 'caught))
(define (unique xs)
  (if (null? xs) '()
      (cons (car xs) (unique (remove-equal (car xs) (cdr xs))))))
(define (remove-equal x xs)
  (cond ((null? xs) '()) ((equal? x (car xs)) (remove-equal x (cdr xs)))
        (else (cons (car xs) (remove-equal x (cdr xs))))))
(define (select p xs)
  (cond ((null? xs) '()) ((p (car xs)) (cons (car xs) (select p (cdr xs))))
        (else (select p (cdr xs)))))
(define (tag? x tag) (and (pair? x) (eq? (car x) tag)))
(define basic-ops (list (list '+ +) (list '- -) (list '* *) (list '= =) (list '< <)
                        (list '> >) (list 'cons cons) (list 'car car) (list 'cdr cdr)
                        (list 'null? null?) (list 'set-cdr! set-cdr!)))

(define (make-machine operations controller)
  (let ((registers '()) (labels '()) (texts '()) (code #f)
        (pc 0) (flag #f) (stack '()) (pushes 0) (depth 0) (maximum 0)
        (steps 0) (trace '()) (trace-limit 0))
    (define (allocate name)
      (if (not (assq name registers))
          (set! registers (cons (cons name '*unassigned*) registers))))
    (define (get name)
      (let ((r (assq name registers)))
        (if (not r) (error "unknown register" name)
            (if (eq? (cdr r) '*unassigned*) (error "unassigned register" name) (cdr r)))))
    (define (put name value)
      (let ((r (assq name registers)))
        (if r (set-cdr! r value) (error "unknown register" name))))
    (define (label-address name)
      (let ((p (assq name labels)))
        (if p (cdr p) (error "undefined label" name))))
    (define (scan-registers x)
      (if (pair? x)
          (cond ((tag? x 'reg) (allocate (cadr x)))
                ((tag? x 'const) 'constant-data)
                ;; List tails are not expressions: a register may be named const or reg.
                (else (for-each scan-registers x)))))
    ;; Pass 1 assigns label addresses and discovers ALL registers (5.13).
    (define (scan xs index)
      (if (not (null? xs))
          (let ((x (car xs)))
            (if (symbol? x)
                (begin
                  (if (assq x labels) (error "duplicate label" x))
                  (set! labels (cons (cons x index) labels))
                  (scan (cdr xs) index))
                (begin
                  (if (memq (car x) '(assign save restore)) (allocate (cadr x)))
                  (scan-registers x)
                  (set! texts (cons x texts))
                  (scan (cdr xs) (+ index 1)))))))
    (define (primitive exp)
      (cond ((tag? exp 'const) (lambda () (cadr exp)))
            ((tag? exp 'reg) (let ((r (cadr exp))) (lambda () (get r))))
            ((tag? exp 'label) (let ((a (label-address (cadr exp)))) (lambda () a)))
            (else (error "bad primitive expression" exp))))
    (define (value-proc expressions)
      (if (tag? (car expressions) 'op)
          (let* ((name (cadar expressions)) (binding (assq name operations))
                 (args (map primitive (cdr expressions))))
            (if (not binding) (error "unknown operation" name))
            (lambda () (apply (cadr binding) (map (lambda (p) (p)) args))))
          (if (= (length expressions) 1) (primitive (car expressions))
              (error "bad value expression" expressions))))
    (define (advance) (set! pc (+ pc 1)))
    ;; Pass 2 closes over resolved operations/addresses, not source evaluation.
    (define (assemble-one text)
      (let ((kind (car text)))
        (cond
          ((eq? kind 'assign)
           (let ((r (cadr text)) (p (value-proc (cddr text))))
             (lambda () (put r (p)) (advance))))
          ((eq? kind 'test)
           (let ((p (value-proc (cdr text)))) (lambda () (set! flag (p)) (advance))))
          ((eq? kind 'perform)
           (let ((p (value-proc (cdr text)))) (lambda () (p) (advance))))
          ((eq? kind 'branch)
           (if (not (tag? (cadr text) 'label)) (error "branch requires label" text))
           (let ((dest (label-address (cadadr text))))
             (lambda () (if flag (set! pc dest) (advance)))))
          ((eq? kind 'goto)
           (if (not (memq (caadr text) '(reg label))) (error "bad goto" text))
           (let ((dest (primitive (cadr text)))) (lambda () (set! pc (dest)))))
          ((eq? kind 'save)
           (let ((r (cadr text)))
             (lambda () (set! stack (cons (cons r (get r)) stack))
               (set! pushes (+ pushes 1)) (set! depth (+ depth 1))
               (set! maximum (max maximum depth)) (advance))))
          ((eq? kind 'restore)
           (let ((r (cadr text)))
             (lambda ()
               (if (null? stack) (error "empty stack" r))
               ;; Tagged saves catch controller bugs; valid textbook code is unchanged.
               (if (not (eq? r (caar stack))) (error "restore register mismatch" r (caar stack)))
               (put r (cdar stack)) (set! stack (cdr stack))
               (set! depth (- depth 1)) (advance))))
          (else (error "unknown instruction" text)))))
    (define (run entry budget)
      (set! pc (if (symbol? entry) (label-address entry) entry))
      (set! stack '()) (set! pushes 0) (set! depth 0) (set! maximum 0)
      (set! steps 0) (set! trace '())
      (define (loop remaining)
        (cond ((= pc (vector-length code)) 'done)
              ((or (not (integer? pc)) (< pc 0) (> pc (vector-length code)))
               (error "invalid pc" pc))
              ((= remaining 0) (error "instruction budget exhausted" steps))
              (else
               (if (< steps trace-limit)
                   (set! trace (cons (list pc (list-ref texts pc) depth) trace)))
               ((vector-ref code pc)) (set! steps (+ steps 1))
               (loop (- remaining 1)))))
      (loop budget))
    (define (analysis)
      (let* ((instructions (unique texts))
             (grouped (apply append
                            (map (lambda (kind) (select (lambda (i) (eq? (car i) kind)) instructions))
                                 '(assign branch goto perform restore save test))))
             (assignments (select (lambda (i) (eq? (car i) 'assign)) texts)))
        (list
         (cons 'instructions grouped)
         (cons 'entry-registers
               (unique (map cadadr (select (lambda (i) (and (eq? (car i) 'goto)
                                                            (tag? (cadr i) 'reg))) texts))))
         (cons 'stack-registers
               (unique (map cadr (select (lambda (i) (memq (car i) '(save restore))) texts))))
         (cons 'assignment-sources
               (map (lambda (r)
                      (cons r (unique (map cddr (select (lambda (i) (eq? (cadr i) r)) assignments)))))
                    (map car (reverse registers)))))))
    (scan controller 0)
    (set! texts (reverse texts))
    (set! code (list->vector (map assemble-one texts)))
    (lambda (message . args)
      (cond ((eq? message 'get) (get (car args)))
            ((eq? message 'set) (put (car args) (cadr args)))
            ((eq? message 'address) (label-address (car args)))
            ((eq? message 'run) (run (car args) (if (null? (cdr args)) 1000000 (cadr args))))
            ((eq? message 'statistics) (list pushes maximum steps depth))
            ((eq? message 'analysis) (analysis))
            ((eq? message 'registers) (map car registers))
            ((eq? message 'trace-limit) (set! trace-limit (car args)))
            ((eq? message 'trace) (reverse trace))
            (else (error "unknown machine message" message))))))
