#lang sicp
(#%require "../05-02-simulator/machine.rkt")
;; Pair pointers are tagged; integers such as 1 must not be mistaken for addresses.
(define (pointer i) (cons 'p i))
(define (pointer? x) (and (pair? x) (eq? (car x) 'p)))
(define (make-heap capacity)
  (if (or (not (integer? capacity)) (not (exact? capacity)) (< capacity 0))
      (error "invalid heap capacity" capacity))
  (let ((cars (make-vector (+ capacity 1) #f))
        (cdrs (make-vector (+ capacity 1) #f)) (free 1) (moves '())
        (broken-heart (list 'private-broken-heart)))
    (define (index p)
      (if (or (not (pointer? p)) (not (integer? (cdr p))) (not (exact? (cdr p)))
              (< (cdr p) 1) (>= (cdr p) free)) (error "invalid pointer" p))
      (cdr p))
    (define (validate-value value) (if (pointer? value) (index value)))
    (define (allocate a d)
      (validate-value a) (validate-value d)
      (if (> free capacity) (error "heap full: collect with complete roots before retry"))
      (let ((p (pointer free)))
        (vector-set! cars free a) (vector-set! cdrs free d)
        (set! free (+ free 1)) p))
    ;; Cheney scan/free algorithm, SICP §5.3.2. Broken hearts preserve sharing/cycles.
    (define (collect roots)
      ;; Validate every root before destructive forwarding. Edges were checked on writes.
      (define (validate-roots xs)
        (cond ((null? xs) 'ok)
              ((not (pair? xs)) (error "roots must be a proper list" roots))
              (else (validate-value (car xs)) (validate-roots (cdr xs)))))
      (validate-roots roots)
      (let ((old-cars cars) (old-cdrs cdrs) (old-free free)
            (new-cars (make-vector (+ capacity 1) #f))
            (new-cdrs (make-vector (+ capacity 1) #f)) (scan 1) (next 1))
        (define (relocate value)
          (if (not (pointer? value)) value
              (let ((i (cdr value)))
                (if (or (< i 1) (>= i old-free)) (error "invalid GC root/edge" value))
                (if (eq? (vector-ref old-cars i) broken-heart)
                    (vector-ref old-cdrs i)
                    (let ((p (pointer next)))
                      (vector-set! new-cars next (vector-ref old-cars i))
                      (vector-set! new-cdrs next (vector-ref old-cdrs i))
                      (vector-set! old-cars i broken-heart)
                      (vector-set! old-cdrs i p)
                      (set! moves (cons (list value '-> p) moves))
                      (set! next (+ next 1)) p)))))
        (set! moves '())
        (let ((new-roots (map relocate roots)))
          (define (scan-loop)
            (if (< scan next)
                (begin
                  (vector-set! new-cars scan (relocate (vector-ref new-cars scan)))
                  (vector-set! new-cdrs scan (relocate (vector-ref new-cdrs scan)))
                  (set! scan (+ scan 1)) (scan-loop))))
          (scan-loop)
          (set! cars new-cars) (set! cdrs new-cdrs) (set! free next)
          new-roots)))
    (lambda (message . args)
      (cond ((eq? message 'cons) (allocate (car args) (cadr args)))
            ((eq? message 'car) (vector-ref cars (index (car args))))
            ((eq? message 'cdr) (vector-ref cdrs (index (car args))))
            ((eq? message 'set-cdr!)
             (validate-value (cadr args))
             (vector-set! cdrs (index (car args)) (cadr args)))
            ((eq? message 'free) free)
            ((eq? message 'collect) (collect (car args)))
            ((eq? message 'moves) (reverse moves))
            ((eq? message 'vectors) (list cars cdrs))
            (else (error "unknown heap message" message))))))
(define (heap-list heap xs)
  (if (null? xs) '() (heap 'cons (car xs) (heap-list heap (cdr xs)))))
(define (heap->list heap p)
  (if (null? p) '() (cons (heap 'car p) (heap->list heap (heap 'cdr p)))))
(define (heap-operations heap)
  (append (list (list 'cons (lambda (a d) (heap 'cons a d)))
                (list 'car (lambda (p) (heap 'car p)))
                (list 'cdr (lambda (p) (heap 'cdr p)))
                (list 'set-cdr! (lambda (p v) (heap 'set-cdr! p v)))) basic-ops))
(define append-controller
  '((assign continue (label done))
    append-loop
    (test (op null?) (reg x))
    (branch (label base))
    (save continue)
    (assign head (op car) (reg x))
    (save head)
    (assign x (op cdr) (reg x))
    (assign continue (label after-append))
    (goto (label append-loop))
    after-append
    (restore head)
    (restore continue)
    (assign val (op cons) (reg head) (reg val))
    (goto (reg continue))
    base
    (assign val (reg y))
    (goto (reg continue))
    done))
(define append!-controller
  '((test (op null?) (reg x))
    (branch (label empty-x))
    (assign val (reg x))
    loop
    (assign next (op cdr) (reg x))
    (test (op null?) (reg next))
    (branch (label splice))
    (assign x (reg next))
    (goto (label loop))
    splice
    (perform (op set-cdr!) (reg x) (reg y))
    (goto (label done))
    empty-x
    (assign val (reg y))
    done))

;; 5.20: explicit allocation order: x, y's tail, y's head.
(define heap (make-heap 32))
(define x (heap 'cons 1 2))
(define tail (heap 'cons x '()))
(define y (heap 'cons x tail))
(check '5.20-x x (pointer 1))
(check '5.20-y y (pointer 3))
(check '5.20-free (heap 'free) 4)
(check 'sharing-before (heap 'car y) (heap 'car (heap 'cdr y)))
(display (list '5.20-vectors (heap 'vectors))) (newline)
;; Unreachable allocation plus a cycle; neither duplication nor infinite relocation.
(heap 'cons 'garbage '())
(define cycle (heap 'cons 'cycle '()))
(heap 'set-cdr! cycle cycle)
(define roots (heap 'collect (list y x cycle)))
(set! y (car roots)) (set! x (cadr roots)) (set! cycle (caddr roots))
(check 'sharing-after (heap 'car y) (heap 'car (heap 'cdr y)))
(check 'multiple-roots (heap 'car y) x)
(check 'cycle (heap 'cdr cycle) cycle)
(check 'live-pairs (heap 'free) 5)
(display (list 'relocations (heap 'moves))) (newline)
(set! roots (heap 'collect roots))
(check 'second-collection (heap 'cdr (caddr roots)) (caddr roots))
(check 'atomic-root (heap 'collect '(7 ())) '(7 ()))
(check 'all-garbage (heap 'free) 1)

(define (run-append controller xs ys)
  (let* ((h (make-heap 32)) (a (heap-list h xs)) (b (heap-list h ys))
         (alias a) (before (h 'free)) (m (make-machine (heap-operations h) controller)))
    (m 'set 'x a) (m 'set 'y b) (m 'run 0)
    (let ((result (m 'get 'val)))
      (check '5.22-result (heap->list h result) (append xs ys))
      (if (eq? controller append-controller)
          (begin (check 'persistent (heap->list h alias) xs)
                 (check 'new-pairs (- (h 'free) before) (length xs)))
          (begin (check 'no-allocation (h 'free) before)
                 (if (not (null? xs))
                     (begin (check 'identity result alias)
                            (check 'alias-observes-splice (heap->list h alias) (append xs ys))))))
      ;; The result shares y, not a copy, for both algorithms.
      (let walk ((p result) (n (length xs)))
        (if (= n 0) (check 'shared-tail p b) (walk (h 'cdr p) (- n 1)))))))
(for-each (lambda (controller)
            (for-each (lambda (case) (run-append controller (car case) (cadr case)))
                      '((() ()) (() (3)) ((1) ()) ((1 2) (3 4)))))
          (list append-controller append!-controller))
(check-error 'heap-full (lambda () (let ((h (make-heap 1))) (h 'cons 1 2) (h 'cons 3 4))))
(check-error 'bad-pointer (lambda () (heap 'car 1)))
(check-error 'bad-capacity (lambda () (make-heap -1)))
(define boundary-heap (make-heap 3))
(define marker-data (boundary-heap 'cons '*broken-heart* '()))
(check-error 'invalid-root-before-mutation
             (lambda () (boundary-heap 'collect (list marker-data (pointer 99)))))
(check 'failed-gc-leaves-heap-intact (boundary-heap 'car marker-data) '*broken-heart*)
(set! marker-data (car (boundary-heap 'collect (list marker-data))))
(check 'marker-symbol-is-ordinary-data (boundary-heap 'car marker-data) '*broken-heart*)
(display "05.03: all checks passed\n")
