#lang sicp
(#%require (only racket/base with-handlers exn:fail?))
;; Wires/gates adapted from SICP §3.3.4. Agenda is a stable sorted event
;; list rather than a list of time-segment queues; both implement FIFO ties.
;; ponytail: O(n) event insertion; use segment queues/heap for large circuits.
(define (make-agenda discipline)
  (if (not (memq discipline '(fifo lifo))) (error "Bad discipline"))
  (let ((time 0) (events '()))
    (define (insert event pending)
      (cond ((null? pending) (list event))
            ((or (< (car event) (caar pending))
                 (and (eq? discipline 'lifo)
                      (= (car event) (caar pending))))
             (cons event pending))
            (else (cons (car pending) (insert event (cdr pending))))))
    (define (schedule delay action)
      (if (< delay 0) (error "Negative delay" delay))
      (set! events (insert (cons (+ time delay) action) events)))
    (define (propagate)
      (if (null? events) 'done
          (let ((event (car events)))
            (set! events (cdr events))
            (set! time (car event))
            ((cdr event))
            (propagate))))
    (lambda (m)
      (cond ((eq? m 'time) time)
            ((eq? m 'schedule) schedule)
            ((eq? m 'propagate) propagate)
            (else (error "Unknown agenda request" m))))))
(define (after-delay agenda delay action) ((agenda 'schedule) delay action))
(define (propagate agenda) ((agenda 'propagate)))
(define (make-wire)
  (let ((signal 0) (actions '()))
    (define (set-signal new)
      (if (not (or (eqv? new 0) (eqv? new 1))) (error "Invalid signal" new))
      (if (not (= signal new))
          (begin (set! signal new) (for-each (lambda (p) (p)) actions))))
    (define (add-action action)
      (set! actions (cons action actions))
      (action))
    (lambda (m)
      (cond ((eq? m 'signal) signal)
            ((eq? m 'set!) set-signal)
            ((eq? m 'add!) add-action)
            (else (error "Unknown wire request" m))))))
(define (get-signal w) (w 'signal))
(define (set-signal! w v) ((w 'set!) v))
(define (add-action! w p) ((w 'add!) p))
(define (binary-gate agenda delay operation a b out)
  (define (action)
    (let ((new (operation (get-signal a) (get-signal b))))
      (after-delay agenda delay (lambda () (set-signal! out new)))))
  (add-action! a action) (add-action! b action) 'ok)
(define (and-gate agenda a b out)
  (binary-gate agenda 3 (lambda (x y) (if (and (= x 1) (= y 1)) 1 0)) a b out))
;; 3.28: a primitive OR, not a composition of other gates.
(define (or-gate agenda a b out)
  (binary-gate agenda 5 (lambda (x y) (if (or (= x 1) (= y 1)) 1 0)) a b out))
(define (inverter agenda in out)
  (define (action)
    (let ((new (- 1 (get-signal in))))
      (after-delay agenda 2 (lambda () (set-signal! out new)))))
  (add-action! in action) 'ok)
(define (half-adder agenda a b sum carry)
  (let ((d (make-wire)) (e (make-wire)))
    (or-gate agenda a b d)
    (and-gate agenda a b carry)
    (inverter agenda carry e)
    (and-gate agenda d e sum)))
(define (check label actual expected)
  (if (not (equal? actual expected)) (error "Check failed" label actual expected)))
(define (ordering-trace discipline)
  (let ((agenda (make-agenda discipline))
        (a (make-wire)) (b (make-wire)) (out (make-wire)) (log '()))
    (set-signal! b 1)
    (and-gate agenda a b out)
    (propagate agenda) ; settled at time 3, inputs 0,1
    (add-action! out (lambda () (set! log (cons (list (agenda 'time) (get-signal out)) log))))
    (set! log '()) ; discard initial observation
    (after-delay agenda 1 (lambda () (set-signal! a 1) (set-signal! b 0)))
    (propagate agenda)
    (list (get-signal out) (reverse log))))
(define (self-check)
  (for-each
   (lambda (row)
     (let ((agenda (make-agenda 'fifo)) (a (make-wire)) (b (make-wire)) (o (make-wire)))
       (or-gate agenda a b o)
       (set-signal! a (car row)) (set-signal! b (cadr row))
       (propagate agenda)
       (check '3.28-truth-table (get-signal o) (caddr row))
       (check 'or-delay (agenda 'time) 5)))
   '((0 0 0) (0 1 1) (1 0 1) (1 1 1)))
  (check '3.32-fifo (ordering-trace 'fifo) '(0 ((7 1) (7 0))))
  (check '3.32-lifo (ordering-trace 'lifo) '(1 ((7 1))))
  (display "3.32 FIFO: ") (display (ordering-trace 'fifo)) (newline)
  (display "3.32 LIFO: ") (display (ordering-trace 'lifo)) (newline)
  (let ((ag (make-agenda 'fifo)) (a (make-wire)) (b (make-wire))
        (s (make-wire)) (c (make-wire)) (log '()))
    (half-adder ag a b s c)
    (add-action! s (lambda () (set! log (cons (list 'sum (ag 'time) (get-signal s)) log))))
    (add-action! c (lambda () (set! log (cons (list 'carry (ag 'time) (get-signal c)) log))))
    (set! log '())
    (set-signal! a 1) (propagate ag)
    (check 'half-adder-first (list (ag 'time) (get-signal s) (get-signal c)) '(8 1 0))
    (set-signal! b 1) (propagate ag)
    (check 'half-adder-events (reverse log) '((sum 8 1) (carry 11 1) (sum 16 0))))
  (let ((ag (make-agenda 'fifo)) (count 0))
    (after-delay ag 0 (lambda () (set! count (+ count 1))
                       (after-delay ag 0 (lambda () (set! count (+ count 1))))))
    (propagate ag) (check 'same-time-new-event count 2)
    (check 'empty-agenda (propagate ag) 'done)
    (check 'negative-delay
           (with-handlers ((exn:fail? (lambda (e) #t)))
             (after-delay ag -1 (lambda () #f)) #f) #t))
  (check 'invalid-signal
         (with-handlers ((exn:fail? (lambda (e) #t))) (set-signal! (make-wire) 2) #f) #t)
  (display "03.04: all checks passed") (newline))
(self-check)
