#lang sicp
(#%require "streams.rkt" (only racket/base with-handlers exn:fail?))
;; Unmemoized counterpart: every cdr is an ordinary nullary procedure.
(define (n-cdr s) ((cdr s)))
(define (n-range low high)
  (if (> low high) '() (cons low (lambda () (n-range (+ low 1) high)))))
(define (n-map p s)
  (if (null? s) '() (cons (p (car s)) (lambda () (n-map p (n-cdr s))))))
(define (n-filter p s)
  (cond ((null? s) '())
        ((p (car s)) (cons (car s) (lambda () (n-filter p (n-cdr s)))))
        (else (n-filter p (n-cdr s)))))
(define (n-ref s n)
  (if (= n 0) (car s) (n-ref (n-cdr s) (- n 1))))
(define (n->list s)
  (if (null? s) '() (cons (car s) (n->list (n-cdr s)))))
;; 3.52: same experiment, parameterized ONLY over memoized/unmemoized mechanics.
(define (experiment map-stream filter-stream range ref to-list)
  (let ((sum 0) (calls 0))
    (define (accum x) (set! calls (+ calls 1)) (set! sum (+ sum x)) sum)
    (define (snapshot) (list sum calls))
    (let* ((initial (snapshot))
           (seq (map-stream accum (range 1 20)))
           (after-seq (snapshot))
           (y (filter-stream even? seq))
           (after-y (snapshot))
           (z (filter-stream (lambda (x) (= (remainder x 5) 0)) seq))
           (after-z (snapshot))
           (eighth (ref y 7))
           (after-ref (snapshot))
           (printed-values (to-list z))
           (after-display (snapshot)))
      (list (list initial after-seq after-y after-z after-ref after-display)
            eighth printed-values))))
(define (check label actual expected)
  (if (not (equal? actual expected)) (error "Check failed" label actual expected)))
(define (raises? thunk)
  (with-handlers ((exn:fail? (lambda (e) #t))) (thunk) #f))
(define (self-check)
  (check '3.50-two
         (stream->list (stream-map + (list->stream '(1 2 3)) (list->stream '(10 20 30))))
         '(11 22 33))
  (check '3.50-three
         (stream->list (stream-map + (list->stream '(1 2)) (list->stream '(10 20))
                                    (list->stream '(100 200)))) '(111 222))
  (check 'shortest (stream->list (stream-map + (list->stream '(1 2)) (list->stream '(10)))) '(11))
  (check 'empty (stream-take (stream-map + (list->stream '(1)) the-empty-stream) 3) '())
  (check 'no-streams (raises? (lambda () (stream-map +))) #t)
  (check 'negative-index (raises? (lambda () (stream-ref (integers-starting-from 1) -1))) #t)
  (check 'past-end (raises? (lambda () (stream-ref the-empty-stream 0))) #t)
  (check 'infinite-prefix (stream-take (integers-starting-from 1) 5) '(1 2 3 4 5))
  (let ((count 0))
    (let ((s (cons-stream 'head (begin (set! count (+ count 1)) the-empty-stream))))
      (check 'head-does-not-force count 0)
      (stream-cdr s) (stream-cdr s)
      (check 'native-memoization count 1)))
  (let ((count 0))
    (let ((p (memo-proc (lambda () (set! count (+ count 1)) #f))))
      (check 'false-result (p) #f) (p) (check 'false-is-cached count 1)))
  (let ((memo (experiment stream-map stream-filter stream-enumerate-interval stream-ref stream->list))
        (plain (experiment n-map n-filter n-range n-ref n->list)))
    (check '3.52-memo memo
           '(((0 0) (1 1) (6 3) (10 4) (136 16) (210 20))
             136 (10 15 45 55 105 120 190 210)))
    (check '3.52-plain plain
           '(((0 0) (1 1) (6 3) (15 6) (162 20) (362 36))
             162 (15 180 230 305)))
    (display "3.52 memo: ") (display memo) (newline)
    (display "3.52 plain: ") (display plain) (newline))
  (display "03.07: all checks passed") (newline))
(self-check)
