#lang sicp
(#%require (only racket/base with-handlers exn:fail?))
;; Close adaptations of SICP §3.2 exercises 3.10 and 3.11.
(define (make-withdraw initial-amount)
  (let ((balance initial-amount))
    (lambda (amount)
      (if (>= balance amount)
          (begin (set! balance (- balance amount)) balance)
          "Insufficient funds"))))
(define (make-account balance)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount)) balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount)) balance)
  (define (dispatch message)
    (cond ((eq? message 'withdraw) withdraw)
          ((eq? message 'deposit) deposit)
          (else (error "Unknown account request" message))))
  dispatch)
(define (check label actual expected)
  (if (not (equal? actual expected))
      (error "Check failed" label actual expected)))
(define (self-check)
  (let ((w1 (make-withdraw 100)))
    (check '3.10-w1 (w1 50) 50)
    (let ((w2 (make-withdraw 100)))
      (check '3.10-w2 (w2 0) 100)
      (check '3.10-independent (w1 0) 50)
      (check 'insufficient (w1 51) "Insufficient funds")
      (check 'no-write-on-failure (w1 0) 50)))
  (let ((acc (make-account 50)))
    (check '3.11-deposit ((acc 'deposit) 40) 90)
    (check '3.11-withdraw ((acc 'withdraw) 60) 30)
    (let ((acc2 (make-account 100)) (saved-deposit (acc 'deposit)))
      (check 'second-account ((acc2 'withdraw) 0) 100)
      (check 'saved-closure (saved-deposit 5) 35)
      (check 'same-parent-frame ((acc 'withdraw) 0) 35)
      (check 'unknown-request
             (with-handlers ((exn:fail? (lambda (e) #t)))
               (acc 'unknown) #f)
             #t)))
  (display "03.02: all checks passed") (newline))
(self-check)
