#lang sicp
(#%require "../04-01-metacircular/evaluator.rkt")
(#%provide analyze analyzed-apply)
;; SICP §4.1.7 adaptation. A compiled host closure receives only an environment.
(define (analyze-sequence body)
  (if (null? body) (error "Empty analyzed sequence")
      (let ((first (analyze (car body))))
        (if (null? (cdr body)) first
            (let ((rest (analyze-sequence (cdr body))))
              (lambda (env) (first env) (rest env)))))))
(define (execute-operands procs env)
  (if (null? procs) '()
      (let ((first ((car procs) env)))
        (cons first (execute-operands (cdr procs) env)))))
(define (analyzed-apply p args)
  (cond ((tagged? p 'primitive) (primitive-apply p args))
        ((tagged? p 'analyzed)
         ((caddr p) (extend (cadr p) args (cadddr p))))
        (else (error "Not an analyzed procedure" p))))
(define (analyze e)
  (cond ((literal? e) (lambda (env) e))
        ((symbol? e) (lambda (env) (lookup e env)))
        ((tagged? e 'quote) (let ((text (cadr e))) (lambda (env) text)))
        ((derived? e) (analyze (expand e)))
        ((tagged? e 'if)
         (let ((p (analyze (cadr e))) (yes (analyze (caddr e)))
               (no (analyze (alternative e))))
           (lambda (env) (if (truth? (p env)) (yes env) (no env)))))
        ((tagged? e 'lambda)
         (let ((parameters (cadr e)) (body (analyze-sequence (scan-out-defines (cddr e)))))
           (lambda (env) (list 'analyzed parameters body env))))
        ((tagged? e 'begin) (analyze-sequence (cdr e)))
        ((tagged? e 'define)
         (let ((name (def-name e)) (value (analyze (def-value e))))
           (lambda (env) (define! name (value env) env))))
        ((tagged? e 'set!)
         (let ((name (cadr e)) (value (analyze (caddr e))))
           (lambda (env) (assign! name (value env) env))))
        ((pair? e)
         (let ((operator (analyze (car e))) (operands (map analyze (cdr e))))
           (lambda (env)
             (let ((p (operator env))) (analyzed-apply p (execute-operands operands env))))))
        (else (error "Unknown analyzed expression" e))))
