#lang sicp
(#%require "../04-01-metacircular/evaluator.rkt" "analyzer.rkt"
           (only racket/base current-inexact-milliseconds))
(define mutual
  '((lambda (n)
      (define (even? k) (if (= k 0) #t (odd? (- k 1))))
      (define (odd? k) (if (= k 0) #f (even? (- k 1))))
      (even? n)) 20))
(define (repeat n action)
  (if (> n 0) (begin (action) (repeat (- n 1) action))))
(define (elapsed action)
  (let ((start (current-inexact-milliseconds)))
    (action) (- (current-inexact-milliseconds) start)))
(define (benchmark label expression count expected)
  (let* ((direct-env (setup)) (analyzed-env (setup)) (code (analyze expression)))
    (check label (mc-eval expression direct-env) expected)
    (check label (code analyzed-env) expected)
    ;; Warm both paths; measurements include neither setup nor printing.
    (repeat 30 (lambda () (mc-eval expression direct-env) (code analyzed-env)))
    (let* ((direct (elapsed (lambda () (repeat count (lambda () (mc-eval expression direct-env))))))
           (execution (elapsed (lambda () (repeat count (lambda () (code analyzed-env))))))
           (analysis (elapsed (lambda () (repeat count (lambda () (analyze expression)))))))
      (display label)
      (display " ms [direct, analyzed-execution, analysis-only, estimated-eliminated-fraction]: ")
      (display (list direct execution analysis (if (> direct 0) (/ (- direct execution) direct) 0)))
      (newline))))
(define (self-check)
  (check 'exercise-4.16b
         (scan-out-defines '((define u 1) (define (v x) (+ u x)) (v 2)))
         '((let ((u '*unassigned*) (v '*unassigned*))
             (set! u 1) (set! v (lambda (x) (+ u x))) (v 2))))
  (check 'no-definitions (scan-out-defines '((+ 1 2))) '((+ 1 2)))
  (check 'quoted-definition (scan-out-defines '((quote (define x 2)))) '((quote (define x 2))))
  (check 'mutual-direct (mc-eval mutual (setup)) #t)
  (check 'mutual-analyzed ((analyze mutual) (setup)) #t)
  (for-each
   (lambda (evaluate)
     (check-error 'exercise-4.16a
                  (lambda () (evaluate '(let ((a 1))
                                         ((lambda () (define b (+ a 10)) (define a 5) (+ a b)))))))
     (check 'early-closure (evaluate '((lambda () (define (f) a) (define a 5) (f)))) 5))
   (list (lambda (e) (mc-eval e (setup))) (lambda (e) ((analyze e) (setup)))))
  (let* ((env (setup)) (code (analyze '(+ x 1))))
    (define! 'x 3 env) (check 'runtime-lookup (code env) 4)
    (assign! 'x 9 env) (check 'not-constant-folding (code env) 10))
  (benchmark 'arithmetic '(+ (* 2 3) (- 9 4)) 15000 11)
  (benchmark 'factorial
             '(begin (define (fact n) (if (= n 0) 1 (* n (fact (- n 1))))) (fact 12))
             2000 479001600)
  (benchmark 'tail-loop
             '(begin (define (loop n acc) (if (= n 0) acc (loop (- n 1) (+ acc n))))
                     (loop 100 0)) 400 5050)
  (display "04.02: all checks passed") (newline))
(self-check)
