#lang sicp
(#%require "../05-02-simulator/machine.rkt" "controllers.rkt")
(define (factorial n)
  (if (= n 0) 1 (* n (factorial (- n 1)))))
(for-each
 (lambda (n)
   (let ((m (make-machine basic-ops iterative-factorial-controller)))
     (m 'set 'n n) (m 'run 0)
     (check '5.1 (m 'get 'product) (factorial n))
     (check 'no-stack (car (m 'statistics)) 0)))
 '(0 1 2 3 5 8))
(for-each
 (lambda (case)
   (let ((b (car case)) (n (cadr case)) (expected (caddr case)))
     (for-each
      (lambda (controller)
        (let ((m (make-machine basic-ops controller)))
          (m 'set 'b b) (m 'set 'n n) (m 'run 0)
          (check '5.4 (m 'get (if (eq? controller recursive-expt-controller) 'val 'product)) expected)
          (check 'balanced-stack (cadddr (m 'statistics)) 0)))
      (list recursive-expt-controller iterative-expt-controller))))
 '((2 0 1) (2 5 32) (-2 3 -8) (0 3 0) (3/2 2 9/4)))
(define traced (make-machine basic-ops factorial-controller))
(traced 'set 'n 3)
(traced 'trace-limit 12)
(traced 'run 0)
(check 'recursive-factorial (traced 'get 'val) 6)
(for-each (lambda (row) (display row) (newline)) (traced 'trace))
(display "05.01: all checks passed\n")
