#lang sicp
(#%require "../05-02-simulator/machine.rkt" "../05-04-explicit-evaluator/runtime.rkt"
           "../05-04-explicit-evaluator/evaluator.rkt" "compiler.rkt")
(define first (make-instruction-sequence '(env) '(env val) '((assign env (const changed)))))
(define second (make-instruction-sequence '(env val) '(val) '((assign val (reg env)))))
(define protected (preserving '(env) first second))
(check 'needs (registers-needed protected) '(env))
(check 'modifies (registers-modified protected) '(val))
(check 'preserving (statements protected)
       '((save env) (assign env (const changed)) (restore env) (assign val (reg env))))
(check 'no-unnecessary-save
       (statements (preserving '(proc) first second))
       '((assign env (const changed)) (assign val (reg env))))
(check-error 'bad-return-target (lambda () (compile '(f) 'argl 'return)))
(define (saved-registers expression)
  (map cadr (select (lambda (i) (and (pair? i) (eq? (car i) 'save)))
                    (statements (compile expression 'val 'next)))))
(check '5.31-generated-saves
       (map saved-registers '((f 'x 'y) ((f) 'x 'y) (f (g 'x) y) (f (g 'x) 'y)))
       '(() () (proc argl) (proc argl)))
(for-each (lambda (x) (display (list '5.31 x (saved-registers x))) (newline))
          '((f 'x 'y) ((f) 'x 'y) (f (g 'x) y) (f (g 'x) 'y)))
(define (measure definition name)
  (let* ((code (statements (compile definition 'val 'next)))
         (machine (make-language-machine code)) (env (setup-environment)))
    (check 'definition (execute-compiled machine env) 'ok)
    (for-each
     (lambda (n)
       (check '5.33-value (evaluate-on-machine machine (list 'factorial n) env)
              (let loop ((k n)) (if (= k 1) 1 (* k (loop (- k 1))))))
       (let ((s (machine 'statistics)))
         (check '5.33-pushes (car s) (+ (* 6 n) 1))
         (check '5.33-depth (cadr s) (max 3 (- (* 3 n) 1)))
         (check '5.33-instruction-count (caddr s) (+ (* 47 n) 32)))
       (display (list name n (machine 'statistics))) (newline))
     '(1 2 3 4 5 8))
    (display (list name 'static-instructions (length (select pair? code))
                   'saves (length (select (lambda (i) (and (pair? i) (eq? (car i) 'save))) code))))
    (newline)))
(measure recursive-factorial 'factorial)
(measure alternate-factorial 'factorial-alt)
;; Source → instructions → assembly → execution, including a non-val target.
(define target-machine (make-language-machine (statements (compile '(+ 2 3) 'argl 'next))))
(execute-compiled target-machine (setup-environment))
(check 'target (target-machine 'get 'argl) 5)
(display "05.05: all checks passed\n")
