#lang sicp
(#%require "../04-01-metacircular/evaluator.rkt")
(#%provide amb-analyze amb-all amb-install!)
;; SICP §4.3.3 adaptation: execution procedures take env, succeed, fail.
;; succeed receives value AND the next failure continuation.
(define (amb-sequence expressions)
  (if (null? expressions) (error "Empty amb sequence")
      (let ((first (amb-analyze (car expressions))))
        (if (null? (cdr expressions)) first
            (let ((rest (amb-sequence (cdr expressions))))
              (lambda (env succeed fail)
                (first env (lambda (ignored fail2) (rest env succeed fail2)) fail)))))))
(define (amb-args procs env succeed fail)
  (if (null? procs) (succeed '() fail)
      ((car procs) env
       (lambda (value fail2)
         (amb-args (cdr procs) env
                   (lambda (values fail3) (succeed (cons value values) fail3)) fail2)) fail)))
(define (amb-apply p args succeed fail)
  (cond ((tagged? p 'primitive) (succeed (primitive-apply p args) fail))
        ((tagged? p 'amb-procedure)
         ((caddr p) (extend (cadr p) args (cadddr p)) succeed fail))
        (else (error "Not an amb procedure" p))))
(define (amb-analyze e)
  (cond ((literal? e) (lambda (env succeed fail) (succeed e fail)))
        ((symbol? e) (lambda (env succeed fail) (succeed (lookup e env) fail)))
        ((tagged? e 'quote)
         (let ((text (cadr e))) (lambda (env succeed fail) (succeed text fail))))
        ((derived? e) (amb-analyze (expand e)))
        ((tagged? e 'amb)
         (let ((choices (map amb-analyze (cdr e))))
           (lambda (env succeed fail)
             (define (try-next rest)
               (if (null? rest) (fail)
                   ((car rest) env succeed (lambda () (try-next (cdr rest))))))
             (try-next choices))))
        ((tagged? e 'if)
         (let ((p (amb-analyze (cadr e))) (yes (amb-analyze (caddr e)))
               (no (amb-analyze (alternative e))))
           (lambda (env succeed fail)
             (p env (lambda (value fail2)
                      (if (truth? value) (yes env succeed fail2) (no env succeed fail2))) fail))))
        ((tagged? e 'lambda)
         (let ((parameters (cadr e)) (body (amb-sequence (scan-out-defines (cddr e)))))
           (lambda (env succeed fail) (succeed (list 'amb-procedure parameters body env) fail))))
        ((tagged? e 'begin) (amb-sequence (cdr e)))
        ((tagged? e 'define)
         (let ((name (def-name e)) (value (amb-analyze (def-value e))))
           (lambda (env succeed fail)
             (value env (lambda (v fail2) (define! name v env) (succeed 'ok fail2)) fail))))
        ((tagged? e 'set!)
         (let ((name (cadr e)) (value (amb-analyze (caddr e))))
           (lambda (env succeed fail)
             (value env
                    (lambda (v fail2)
                      (let* ((cell (binding name env)) (old (cdr cell)))
                        (set-cdr! cell v)
                        (succeed 'ok (lambda () (set-cdr! cell old) (fail2))))) fail))))
        ((pair? e)
         (let ((operator (amb-analyze (car e))) (operands (map amb-analyze (cdr e))))
           (lambda (env succeed fail)
             (operator env
                       (lambda (p fail2)
                         (amb-args operands env
                                   (lambda (args fail3) (amb-apply p args succeed fail3)) fail2)) fail))))
        (else (error "Unknown amb expression" e))))
(define (amb-all expression env)
  (let ((answers '()))
    ((amb-analyze expression) env
     (lambda (value next) (set! answers (cons value answers)) (next))
     (lambda () (reverse answers)))))
(define (amb-install! expression env)
  ((amb-analyze expression) env (lambda (value next) value)
   (lambda () (error "Installation failed" expression))))
