#lang sicp
(#%require "../04-01-metacircular/evaluator.rkt" "amb-evaluator.rkt")
(define env (setup))
(define program
  '(begin
     (define (require p) (if (not p) (amb) 'ok))
     (define (an-integer-between low high)
       (if (not (and (integer? low) (integer? high))) (error "Integer bounds required"))
       (require (<= low high))
       (amb low (an-integer-between (+ low 1) high)))
     (define (a-pythagorean-triple-between low high)
       (let ((i (an-integer-between low high)))
         (let ((j (an-integer-between i high)))
           (let ((k (an-integer-between j high)))
             (require (= (+ (* i i) (* j j)) (* k k)))
             (list i j k)))))
     (define (daughter-except yacht used)
       (let ((name (amb 'MaryAnn 'Gabrielle 'Lorna 'Rosalind 'Melissa)))
         (require (not (eq? name yacht)))
         (require (not (member name used)))
         name))
     (define (yachts mary-is-moore?)
       ;; The fixed Hood daughter prunes before any choices are made.
       (let ((hood 'Melissa))
         (let ((moore (if mary-is-moore? 'MaryAnn (daughter-except 'Lorna (list hood)))))
           (let ((downing (daughter-except 'Melissa (list hood moore))))
             (let ((hall (daughter-except 'Rosalind (list hood moore downing))))
               (let ((parker (daughter-except 'MaryAnn (list hood moore downing hall))))
                 (require
                  (cond ((eq? moore 'Gabrielle) (eq? parker 'Lorna))
                        ((eq? downing 'Gabrielle) (eq? parker 'Melissa))
                        ((eq? hall 'Gabrielle) (eq? parker 'Rosalind))
                        ;; Hood is Melissa; Parker cannot both be Gabrielle
                        ;; and have daughter MaryAnn as his yacht would require.
                        ((eq? parker 'Gabrielle) (eq? parker 'MaryAnn))
                        (else #f)))
                 (list (list 'Moore moore) (list 'Downing downing)
                       (list 'Hall hall) (list 'Hood hood) (list 'Parker parker))))))))))
(define (self-check)
  (amb-install! program env)
  (check 'choice-order (amb-all '(list (amb 1 2) (amb 3 4)) env) '((1 3) (1 4) (2 3) (2 4)))
  (check 'empty-choice (amb-all '(amb) env) '())
  (check 'exercise-4.35-range (amb-all '(an-integer-between -1 1) env) '(-1 0 1))
  (check 'singleton (amb-all '(an-integer-between 2 2) env) '(2))
  (check 'empty-range (amb-all '(an-integer-between 3 2) env) '())
  (check-error 'noninteger (lambda () (amb-all '(an-integer-between 1/2 3) env)))
  (let ((triples (amb-all '(a-pythagorean-triple-between 1 20) env)))
    (check 'exercise-4.35 triples '((3 4 5) (5 12 13) (6 8 10) (8 15 17) (9 12 15) (12 16 20)))
    (display triples) (newline))
  (check 'no-triples (amb-all '(a-pythagorean-triple-between 1 4) env) '())
  (check 'textbook-nonstrict-bound
         (amb-all '(a-pythagorean-triple-between 0 1) env) '((0 0 0) (0 1 1)))
  (let ((with-father (amb-all '(yachts #t) env)) (without-father (amb-all '(yachts #f) env)))
    (check 'exercise-4.43-fixed with-father
           '(((Moore MaryAnn) (Downing Lorna) (Hall Gabrielle) (Hood Melissa) (Parker Rosalind))))
    (check 'exercise-4.43-relaxed-count (length without-father) 2)
    (check 'exercise-4.43-relaxed without-father
           '(((Moore MaryAnn) (Downing Lorna) (Hall Gabrielle) (Hood Melissa) (Parker Rosalind))
             ((Moore Gabrielle) (Downing Rosalind) (Hall MaryAnn) (Hood Melissa) (Parker Lorna))))
    (display without-father) (newline))
  (amb-install! '(define x 0) env)
  (check 'restore-on-failure
         (amb-all '(amb (begin (set! x 9) (amb)) x) env) '(0))
  (check 'restore-after-enumeration
         (amb-all '(begin (set! x (amb 1 2)) x) env) '(1 2))
  (check 'old-value (lookup 'x env) 0)
  (check-error 'arity (lambda () (amb-all '((lambda (x) x)) env)))
  (display "04.04: all checks passed") (newline))
(self-check)
