#lang sicp
(#%require (only racket/base make-semaphore call-with-semaphore with-handlers exn:fail?))
;; 3.38: deterministic instruction interleavings, not a random thread demo.
(define (serial-balance order)
  (define (step who balance)
    (cond ((eq? who 'P) (+ balance 10))
          ((eq? who 'U) (- balance 20))
          ((eq? who 'M) (- balance (/ balance 2)))
          (else (error "Unknown actor" who))))
  (define (loop order balance)
    (if (null? order) balance (loop (cdr order) (step (car order) balance))))
  (loop order 100))
(define (run-interleaving schedule)
  (let ((balance 100) (p #f) (u #f) (m-left #f) (m-right #f))
    (for-each
     (lambda (event)
       (cond ((eq? event 'Pr) (set! p balance))
             ((eq? event 'Pw) (set! balance (+ p 10)))
             ((eq? event 'Ur) (set! u balance))
             ((eq? event 'Uw) (set! balance (- u 20)))
             ((eq? event 'Ml) (set! m-left balance))
             ((eq? event 'Mr) (set! m-right balance))
             ((eq? event 'Mw) (set! balance (- m-left (/ m-right 2))))
             (else (error "Unknown instruction" event)))) schedule)
    balance))
(define (interleavings a b c)
  (define (prefix x schedules) (map (lambda (s) (cons x s)) schedules))
  (if (and (null? a) (null? b) (null? c)) (list '())
      (append (if (null? a) '() (prefix (car a) (interleavings (cdr a) b c)))
              (if (null? b) '() (prefix (car b) (interleavings a (cdr b) c)))
              (if (null? c) '() (prefix (car c) (interleavings a b (cdr c)))))))
(define (unique xs)
  (if (null? xs) '()
      (if (member (car xs) (cdr xs)) (unique (cdr xs))
          (cons (car xs) (unique (cdr xs))))))

;; 3.48: actual mutex-backed serializers. The host semaphore supplies the
;; atomic acquire/release that a plain Scheme test-then-set cannot supply.
(define lock-log '())
(define (log-lock action id) (set! lock-log (cons (list action id) lock-log)))
(define (make-serializer id)
  (let ((mutex (make-semaphore 1)))
    (lambda (procedure)
      (lambda args
        (call-with-semaphore
         mutex
         (lambda ()
           (dynamic-wind
            (lambda () (log-lock 'acquire id))
            (lambda () (apply procedure args))
            (lambda () (log-lock 'release id)))))))))
(define next-account-id 0)
(define id-mutex (make-semaphore 1))
(define (fresh-id)
  (call-with-semaphore id-mutex
    (lambda () (set! next-account-id (+ next-account-id 1)) next-account-id)))
(define (make-account balance)
  (let* ((id (fresh-id)) (serializer (make-serializer id)))
    ;; Raw signed adjustments used ONLY under the account serializers.
    (define (withdraw amount) (set! balance (- balance amount)) balance)
    (define (deposit amount) (set! balance (+ balance amount)) balance)
    (lambda (message)
      (cond ((eq? message 'id) id)
            ((eq? message 'serializer) serializer)
            ((eq? message 'balance) balance)
            ((eq? message 'withdraw) withdraw)
            ((eq? message 'deposit) deposit)
            (else (error "Unknown account request" message))))))
(define (exchange a b)
  (let ((difference (- (a 'balance) (b 'balance))))
    ((a 'withdraw) difference)
    ((b 'deposit) difference)
    'exchanged))
(define (serialized-exchange a b)
  (if (eq? a b) 'same-account
      (let* ((low (if (< (a 'id) (b 'id)) a b))
             (high (if (< (a 'id) (b 'id)) b a))
             (outer (low 'serializer))
             (inner (high 'serializer)))
        ((outer (inner exchange)) a b))))
(define (check label actual expected)
  (if (not (equal? actual expected)) (error "Check failed" label actual expected)))
(define (self-check)
  (check '3.38-serial
         (map serial-balance '((P U M) (P M U) (U P M) (U M P) (M P U) (M U P)))
         '(45 35 45 50 40 40))
  (check 'lost-updates-110 (run-interleaving '(Pr Ur Ml Mr Mw Uw Pw)) 110)
  (check 'lost-updates-80 (run-interleaving '(Pr Ur Ml Mr Pw Mw Uw)) 80)
  (check 'mary-two-reads-55 (run-interleaving '(Ml Pr Pw Ur Uw Mr Mw)) 55)
  (let* ((schedules (interleavings '(Pr Pw) '(Ur Uw) '(Ml Mr Mw)))
         (balances (unique (map run-interleaving schedules))))
    (check 'all-schedules (length schedules) 210)
    (check 'distinct-balances (length balances) 13)
    (for-each (lambda (n) (check 'included (if (member n balances) #t #f) #t))
              '(25 30 35 40 45 50 55 60 65 70 80 90 110))
    (display "3.38: 210 instruction schedules; balances = ")
    (display balances) (newline))
  (let* ((a (make-account 100)) (b (make-account 40)))
    (check 'distinct-ids (< (a 'id) (b 'id)) #t)
    (set! lock-log '())
    (serialized-exchange b a) ; reversed arguments still acquire a first
    (check 'swapped (list (a 'balance) (b 'balance)) '(40 100))
    (check 'ordered-ids (reverse lock-log)
           (list (list 'acquire (a 'id)) (list 'acquire (b 'id))
                 (list 'release (b 'id)) (list 'release (a 'id))))
    (set! lock-log '())
    (serialized-exchange a b)
    (check 'swapped-back (list (a 'balance) (b 'balance)) '(100 40))
    (check 'same-order (map cadr (reverse lock-log))
           (list (a 'id) (b 'id) (b 'id) (a 'id)))
    (check 'same-account (serialized-exchange a a) 'same-account)
    (check 'exception
           (with-handlers ((exn:fail? (lambda (e) #t)))
             (((a 'serializer) (lambda () (error "Expected failure")))) #f) #t)
    (check 'released-after-exception (((a 'serializer) (lambda () 42))) 42))
  (let* ((a (make-account 50)) (b (make-account 50)))
    (set! lock-log '())
    (serialized-exchange b a)
    (check 'equal-balances (list (a 'balance) (b 'balance)) '(50 50))
    (check 'ids-not-balances (map cadr (reverse lock-log))
           (list (a 'id) (b 'id) (b 'id) (a 'id))))
  (display "03.06: all checks passed") (newline))
(self-check)
