#lang sicp
;; SICP 第二版 §1.2.1–1.2.3，1.9 / 1.11；教材递推式的课程实现。
(#%require (only racket/base with-handlers exn:fail?))
(define (natural? n) (and (integer? n) (exact? n) (>= n 0)))
(define (require-natural n)
  (if (not (natural? n)) (error "Expected exact nonnegative integer" n) #t))

;; 1.9：另取名字，避免遮蔽自检和其他解法使用的内建 +。
(define (add-recursive a b)
  (require-natural a) (require-natural b)
  (define (add a b)
    (if (= a 0) b (inc (add (dec a) b))))
  (add a b))
(define (add-iterative a b)
  (require-natural a) (require-natural b)
  (define (iter a b)
    (if (= a 0) b (iter (dec a) (inc b))))
  (iter a b))

(define (factorial-recursive n)
  (require-natural n)
  (define (fact k)
    (if (= k 0) 1 (* k (fact (- k 1)))))
  (fact n))
(define (factorial-iterative n)
  (require-natural n)
  (define (iter product counter)
    (if (> counter n) product
        (iter (* product counter) (+ counter 1))))
  (iter 1 1))

;; 1.11：允许负整数，忠实保留 n < 3 时 f(n)=n 的基例。
(define (require-integer n)
  (if (not (and (integer? n) (exact? n)))
      (error "Expected exact integer" n) #t))
(define (f-recursive n)
  (require-integer n)
  (define (f n)
    (if (< n 3) n
        (+ (f (- n 1)) (* 2 (f (- n 2))) (* 3 (f (- n 3))))))
  (f n))
(define (f-iterative n)
  (require-integer n)
  ;; k 表示当前最高下标；a=f(k), b=f(k-1), c=f(k-2)。
  (define (iter a b c k)
    (if (= k n) a
        (iter (+ a (* 2 b) (* 3 c)) a b (+ k 1))))
  (if (< n 3) n (iter 2 1 0 2)))

(define (fib-tree n)
  (require-natural n)
  (define (fib k)
    (if (< k 2) k (+ (fib (- k 1)) (fib (- k 2)))))
  (fib n))
(define (fib-iterative n)
  (require-natural n)
  (define (iter a b remaining)
    (if (= remaining 0) b
        (iter (+ a b) a (- remaining 1))))
  (iter 1 0 n))

;; count-change 的两个分支：不用这一面额 / 用一枚后仍可继续用。
(define (count-change amount)
  (require-natural amount)
  (define (cc amount coins)
    (cond ((= amount 0) 1)
          ((or (< amount 0) (null? coins)) 0)
          (else (+ (cc amount (cdr coins))
                   (cc (- amount (car coins)) coins)))))
  (cc amount '(50 25 10 5 1)))

(define (check-equal label actual expected)
  (if (not (equal? actual expected))
      (error "Check failed" label actual expected) #t))
(define (raises? thunk)
  (with-handlers ((exn:fail? (lambda (e) #t))) (thunk) #f))
(define (self-check)
  (check-equal 'add-recursive (add-recursive 4 5) 9)
  (check-equal 'add-iterative (add-iterative 4 5) 9)
  (check-equal 'add-zero (add-recursive 0 5) 5)
  (check-equal 'both-zero (add-iterative 0 0) 0)
  (check-equal 'long-tail (add-iterative 100000 7) 100007)
  (for-each (lambda (n)
              (check-equal n (factorial-recursive n) (factorial-iterative n)))
            '(0 1 2 5 10))
  (check-equal 'factorial (factorial-iterative 6) 720)
  (check-equal 'f-values (map f-iterative '(-2 0 1 2 3 4 5 6))
               '(-2 0 1 2 4 11 25 59))
  (for-each (lambda (n) (check-equal n (f-recursive n) (f-iterative n)))
            '(-3 0 1 2 3 4 5 6 7 8 9 10 11 12))
  (check-equal 'fib (fib-tree 10) 55)
  (check-equal 'fib-zero (fib-iterative 0) 0)
  (check-equal 'fib-agreement (fib-tree 15) (fib-iterative 15))
  (check-equal 'empty-change (count-change 0) 1)
  (check-equal 'change-11 (count-change 11) 4)
  (check-equal 'change-dollar (count-change 100) 292)
  (check-equal 'reject-negative
               (raises? (lambda () (add-iterative -1 4))) #t)
  (check-equal 'reject-noninteger
               (raises? (lambda () (f-iterative 3/2))) #t)
  (display "01.03: all checks passed") (newline))
(self-check)
