#lang sicp
(#%provide (all-defined))
;; Syntax/environment interfaces from SICP §4.1.2–4.1.3, adapted for CLI tests.
(define (tagged-list? x tag) (and (pair? x) (eq? (car x) tag)))
(define (self-evaluating? x) (or (number? x) (string? x) (boolean? x)))
(define variable? symbol?)
(define (quoted? x) (tagged-list? x 'quote))
(define text-of-quotation cadr)
(define (assignment? x) (tagged-list? x 'set!))
(define assignment-variable cadr)
(define assignment-value caddr)
(define (definition? x) (tagged-list? x 'define))
(define (definition-variable x) (if (symbol? (cadr x)) (cadr x) (caadr x)))
(define (definition-value x)
  (if (symbol? (cadr x)) (caddr x) (cons 'lambda (cons (cdadr x) (cddr x)))))
(define (if? x) (tagged-list? x 'if))
(define if-predicate cadr)
(define if-consequent caddr)
(define (if-alternative x) (if (null? (cdddr x)) #f (cadddr x)))
(define (lambda? x) (tagged-list? x 'lambda))
(define lambda-parameters cadr)
(define lambda-body cddr)
(define (begin? x) (tagged-list? x 'begin))
(define begin-actions cdr)
(define first-exp car)
(define rest-exps cdr)
(define (last-exp? xs) (null? (cdr xs)))
(define application? pair?)
(define operator car)
(define operands cdr)
(define no-operands? null?)
(define first-operand car)
(define rest-operands cdr)
(define last-operand? last-exp?)
(define (empty-arglist) '())
(define (adjoin-arg arg args) (append args (list arg)))
(define (true? x) (not (eq? x #f)))
(define (false? x) (eq? x #f))
(define (make-procedure parameters body env) (list 'procedure parameters body env))
(define (compound-procedure? p) (tagged-list? p 'procedure))
(define procedure-parameters cadr)
(define procedure-body caddr)
(define procedure-environment cadddr)
(define (make-compiled-procedure entry env) (list 'compiled-procedure entry env))
(define (compiled-procedure? p) (tagged-list? p 'compiled-procedure))
(define compiled-procedure-entry cadr)
(define compiled-procedure-env caddr)

;; Frame = mutable (names . values). Append definitions, preserving parameter offsets.
(define (extend-environment names values base)
  (if (not (= (length names) (length values))) (error "arity mismatch" names values))
  (cons (cons names values) base))
(define (binding-cell name frame)
  (define (walk names values)
    (cond ((null? names) #f) ((eq? name (car names)) values)
          (else (walk (cdr names) (cdr values)))))
  (walk (car frame) (cdr frame)))
(define (lookup-variable-value name env)
  (if (null? env) (error "unbound variable" name)
      (let ((cell (binding-cell name (car env))))
        (if cell (if (eq? (car cell) '*unassigned*) (error "unassigned variable" name) (car cell))
            (lookup-variable-value name (cdr env))))))
(define (set-variable-value! name value env)
  (if (null? env) (error "unbound assignment" name)
      (let ((cell (binding-cell name (car env))))
        (if cell (set-car! cell value) (set-variable-value! name value (cdr env))))))
(define (define-variable! name value env)
  (let* ((frame (car env)) (cell (binding-cell name frame)))
    (if cell (set-car! cell value)
        (begin (set-car! frame (append (car frame) (list name)))
               (set-cdr! frame (append (cdr frame) (list value)))))))
(define (lexical-address-cell address env)
  (if (or (not (= (length address) 2))
          (not (integer? (car address))) (not (integer? (cadr address)))
          (< (car address) 0) (< (cadr address) 0)) (error "bad lexical address" address))
  (list-tail (cdr (list-ref env (car address))) (cadr address)))
(define (lexical-address-lookup address env)
  (let ((value (car (lexical-address-cell address env))))
    (if (eq? value '*unassigned*) (error "unassigned lexical binding" address) value)))
(define (lexical-address-set! address value env)
  (set-car! (lexical-address-cell address env) value))
(define primitives
  (list (list '+ +) (list '- -) (list '* *) (list '= =) (list '> >) (list '< <)
        (list 'cons cons) (list 'car car) (list 'cdr cdr) (list 'list list)
        (list 'null? null?) (list 'eq? eq?) (list 'not not)))
(define (primitive-procedure? p) (tagged-list? p 'primitive))
(define (apply-primitive-procedure p args) (apply (cadr p) args))
(define (setup-environment)
  (extend-environment (map car primitives)
                      (map (lambda (p) (list 'primitive (cadr p))) primitives) '()))
(define (fail kind value) (error "machine evaluation error" kind value))

(define recursive-factorial
  '(define (factorial n) (if (= n 1) 1 (* (factorial (- n 1)) n))))
(define alternate-factorial
  '(define (factorial n) (if (= n 1) 1 (* n (factorial (- n 1))))))
(define iterative-factorial
  '(define (factorial n)
     (define (iter product counter)
       (if (> counter n) product (iter (* counter product) (+ counter 1))))
     (iter 1 1)))
