#lang sicp
(#%require "../05-02-simulator/machine.rkt" "runtime.rkt" "evaluator.rkt")
(define machine (make-language-machine '()))
(define env (setup-environment))
(define (ev x) (evaluate-on-machine machine x env))
(check 'closure (ev '(((lambda (x) (lambda (y) (+ x y))) 8) 3)) 11)
(check 'mutation (ev '(begin (define x 1) (set! x 7) x)) 7)
(check 'false-only (ev '(if 0 1 2)) 1)
(check 'unselected-error (ev '(if #f missing 42)) 42)
(check 'empty-arguments (ev '((lambda () 9))) 9)
(check-error 'unbound (lambda () (ev 'missing)))
(check-error 'arity (lambda () (ev '((lambda (x) x)))))
(define (measure definition mode)
  (ev definition)
  (for-each
   (lambda (n)
     (let ((value (ev (list 'factorial n))) (s (machine 'statistics)))
       (check 'factorial value (let loop ((i n)) (if (= i 0) 1 (* i (loop (- i 1))))))
       (check 'balanced-stack (cadddr s) 0)
       (if (eq? mode 'iterative)
           (begin (check '5.26a (cadr s) 10) (check '5.26b (car s) (+ (* 35 n) 29)))
           (begin (check '5.27-depth (cadr s) (+ (* 5 n) 3))
                  (check '5.27-pushes (car s) (- (* 32 n) 16))))
       (display (list mode n value s)) (newline)))
   '(2 3 4 5 8)))
(measure iterative-factorial 'iterative)
(measure recursive-factorial 'recursive)
(display "05.04: all checks passed\n")
