#lang sicp
(#%require (only racket/base with-handlers exn:fail?))
;; SICP §3.3.1–3.3.3: mutable pairs, queue and one-key table.
(define (last-pair xs)
  (if (null? (cdr xs)) xs (last-pair (cdr xs))))
(define (make-cycle xs) (set-cdr! (last-pair xs) xs) xs)
(define (take-links xs n)
  (if (= n 0) '() (cons (car xs) (take-links (cdr xs) (- n 1)))))
(define (make-queue) (cons '() '()))
(define (empty-queue? q) (null? (car q)))
(define (front-queue q)
  (if (empty-queue? q) (error "Empty queue") (caar q)))
(define (insert-queue! q item)
  (let ((node (cons item '())))
    (if (empty-queue? q)
        (begin (set-car! q node) (set-cdr! q node))
        (begin (set-cdr! (cdr q) node) (set-cdr! q node)))
    q))
;; Retain textbook's stale rear pointer, to reproduce exercise 3.21.
(define (delete-queue! q)
  (if (empty-queue? q)
      (error "Empty queue")
      (begin (set-car! q (cdar q)) q)))
(define (print-queue q) (display (car q)) (newline))
(define (queue-items q) (car q))

(define (make-table)
  (let ((records '()))
    (define (lookup key)
      (let ((record (assoc key records)))
        (if record (cdr record) #f)))
    (define (insert! key value)
      (let ((record (assoc key records)))
        (if record (set-cdr! record value)
            (set! records (cons (cons key value) records))))
      'ok)
    (lambda (message)
      (cond ((eq? message 'lookup) lookup)
            ((eq? message 'insert!) insert!)
            (else (error "Unknown table request" message))))))
(define (check label actual expected)
  (if (not (equal? actual expected))
      (error "Check failed" label actual expected)))
(define (raises? thunk)
  (with-handlers ((exn:fail? (lambda (e) #t))) (thunk) #f))
(define (self-check)
  (let* ((shared (list 'a 'b)) (graph (cons shared shared)))
    (set-car! (car graph) 'changed)
    (check 'alias (car (cdr graph)) 'changed))
  (let ((z (make-cycle (list 'a 'b 'c))))
    (check '3.13-cycle (eq? z (cdddr z)) #t)
    (check 'finite-observation (take-links z 7) '(a b c a b c a)))
  (let ((q (make-queue)))
    (check 'empty-front (raises? (lambda () (front-queue q))) #t)
    (check 'empty-delete (raises? (lambda () (delete-queue! q))) #t)
    (insert-queue! q 'a)
    (check '3.21-one q '((a) a))
    (insert-queue! q 'b)
    (check '3.21-two q '((a b) b))
    (check 'rear-alias (eq? (cdr q) (cdar q)) #t)
    (print-queue q)
    (delete-queue! q)
    (check '3.21-delete-one q '((b) b))
    (delete-queue! q)
    (check '3.21-delete-two q '(() b))
    (check 'empty-despite-rear (empty-queue? q) #t)
    (print-queue q)
    (insert-queue! q 'c)
    (check 'reuse (queue-items q) '(c)))
  (let ((t (make-table)))
    (check 'missing ((t 'lookup) '(math +)) #f)
    ((t 'insert!) '(math +) 10)
    ((t 'insert!) '(math +) 20)
    ((t 'insert!) 'other 7)
    (check 'structural-key-update ((t 'lookup) (list 'math '+)) 20)
    (check 'independent-record ((t 'lookup) 'other) 7))
  (display "03.03: all checks passed") (newline))
(self-check)
