#lang sicp
(#%require (only racket/base with-handlers exn:fail?))
;; Adapted from SICP §2.1: interfaces, not pair layout, define the data.
(define (make-rat n d)
  (if (not (and (integer? n) (exact? n) (integer? d) (exact? d)
                (not (= d 0))))
      (error "rational requires exact integers and nonzero denominator" n d)
      (let ((g (gcd (abs n) (abs d))) (sign (if (< d 0) -1 1)))
        (cons (* sign (/ n g)) (/ (abs d) g)))))
(define (numer r) (car r))
(define (denom r) (cdr r))
(define (add-rat x y)
  (make-rat (+ (* (numer x) (denom y)) (* (numer y) (denom x)))
            (* (denom x) (denom y))))
(define (sub-rat x y)
  (make-rat (- (* (numer x) (denom y)) (* (numer y) (denom x)))
            (* (denom x) (denom y))))
(define (mul-rat x y)
  (make-rat (* (numer x) (numer y)) (* (denom x) (denom y))))
(define (div-rat x y)
  (make-rat (* (numer x) (denom y)) (* (denom x) (numer y))))
(define (equal-rat? x y)
  (= (* (numer x) (denom y)) (* (numer y) (denom x))))
;; 2.4: keep host cons/car/cdr for other course examples.
(define (proc-cons x y) (lambda (m) (m x y)))
(define (proc-car z) (z (lambda (p q) p)))
(define (proc-cdr z) (z (lambda (p q) q)))
;; Same arithmetic body with an alternate representation, localized bindings.
(define (procedural-rat-example)
  (define (make-rat n d)
    (let ((r (make-normalized-rat n d))) (proc-cons (car r) (cdr r))))
  (define numer proc-car)
  (define denom proc-cdr)
  (define (add-rat x y)
    (make-rat (+ (* (numer x) (denom y)) (* (numer y) (denom x)))
              (* (denom x) (denom y))))
  (let ((r (add-rat (make-rat 1 2) (make-rat 1 3))))
    (list (numer r) (denom r))))
(define make-normalized-rat make-rat)
(define (check label actual expected)
  (if (not (equal? actual expected)) (error "check failed" label actual expected)))
(define (check-error label thunk)
  (check label (with-handlers ((exn:fail? (lambda (e) #t))) (thunk) #f) #t))
(define (self-check)
  (for-each (lambda (row)
              (check row (make-rat (car row) (cadr row))
                     (cons (caddr row) (cadddr row))))
            '((2 4 1 2) (-2 4 -1 2) (2 -4 -1 2) (-2 -4 1 2)
              (0 -7 0 1)))
  (check 'add (add-rat (make-rat 1 2) (make-rat 1 3)) (make-rat 5 6))
  (check 'sub (sub-rat (make-rat 1 2) (make-rat 1 3)) (make-rat 1 6))
  (check 'mul (mul-rat (make-rat 1 2) (make-rat 1 3)) (make-rat 1 6))
  (check 'div (div-rat (make-rat 1 2) (make-rat 1 3)) (make-rat 3 2))
  (check 'equality (equal-rat? (make-rat 2 4) (make-rat 1 2)) #t)
  (check-error 'zero-denominator (lambda () (make-rat 1 0)))
  (check-error 'fraction-input (lambda () (make-rat 1/2 3)))
  (check-error 'inexact-input (lambda () (make-rat 1.0 3)))
  (check-error 'divide-zero (lambda () (div-rat (make-rat 1 2) (make-rat 0 3))))
  (let ((x (list 1 2)) (y (lambda (n) (+ n 1))))
    (check 'car-identity (eq? (proc-car (proc-cons x y)) x) #t)
    (check 'cdr-procedure ((proc-cdr (proc-cons x y)) 4) 5))
  (check 'changed-representation (procedural-rat-example) '(5 6))
  (display "02.01: all checks passed") (newline))
(self-check)
