#lang sicp
(#%require "../02-08-multiple-representations/dispatch-core.rkt"
           (only racket/base with-handlers exn:fail?))
;; Separate coercion keys in the shared operation table.
(define (put-coercion from to proc) (put 'coercion (list from to) proc))
(define (get-coercion from to) (get 'coercion (list from to)))
;; 2.81c: exact method first; equal tags with no method fail before coercion.
(define (apply-generic op . args)
  (let* ((tags (map type-tag args)) (proc (get op tags)))
    (cond (proc (apply proc (map contents args)))
          ((and (= (length args) 2) (not (eq? (car tags) (cadr tags))))
           (let ((forward (get-coercion (car tags) (cadr tags)))
                 (backward (get-coercion (cadr tags) (car tags))))
             (cond (forward (apply-generic op (forward (car args)) (cadr args)))
                   (backward (apply-generic op (car args) (backward (cadr args))))
                   (else (error "no method/coercion" op tags)))))
          (else (error "no method for types" op tags)))))
(define (add x y) (apply-generic 'add x y))
(define (sub x y) (apply-generic 'sub x y))
(define (mul x y) (apply-generic 'mul x y))
(define (div x y) (apply-generic 'div x y))
(define (=zero? x) (apply-generic '=zero? x))
(define (generic-exp x y) (apply-generic 'exp x y))
(define (finite-real? x) (and (real? x) (< -inf.0 x +inf.0)))
(define (make-scheme-number x)
  (if (finite-real? x) (attach-tag 'scheme-number x) (error "finite real host number required" x)))
(define (make-rational n d)
  (if (not (and (integer? n) (exact? n) (integer? d) (exact? d) (not (= d 0))))
      (error "exact integer numerator/nonzero denominator required" n d)
      (let ((g (gcd (abs n) (abs d))) (sign (if (< d 0) -1 1)))
        (attach-tag 'rational (cons (* sign (/ n g)) (/ (abs d) g))))))
(define (make-complex x y) (attach-tag 'complex (make-from-real-imag x y)))
(define (install-numbers)
  (for-each (lambda (entry)
              (put (car entry) '(scheme-number scheme-number)
                   (lambda (x y) (make-scheme-number ((cadr entry) x y)))))
            (list (list 'add +) (list 'sub -) (list 'mul *) (list 'div /) (list 'exp expt)))
  (put '=zero? '(scheme-number) (lambda (x) (= x 0)))
  (put 'add '(rational rational)
       (lambda (a b) (make-rational (+ (* (car a) (cdr b)) (* (car b) (cdr a))) (* (cdr a) (cdr b)))))
  (put 'sub '(rational rational)
       (lambda (a b) (make-rational (- (* (car a) (cdr b)) (* (car b) (cdr a))) (* (cdr a) (cdr b)))))
  (put 'mul '(rational rational)
       (lambda (a b) (make-rational (* (car a) (car b)) (* (cdr a) (cdr b)))))
  (put 'div '(rational rational)
       (lambda (a b) (make-rational (* (car a) (cdr b)) (* (cdr a) (car b)))))
  (put '=zero? '(rational) (lambda (a) (= (car a) 0)))
  ;; The outer complex tag is removed; inner representation still dispatches.
  (put 'add '(complex complex)
       (lambda (a b) (make-complex (+ (real-part a) (real-part b)) (+ (imag-part a) (imag-part b)))))
  (put 'sub '(complex complex)
       (lambda (a b) (make-complex (- (real-part a) (real-part b)) (- (imag-part a) (imag-part b)))))
  (put 'mul '(complex complex)
       (lambda (a b) (make-complex (- (* (real-part a) (real-part b)) (* (imag-part a) (imag-part b)))
                                 (+ (* (real-part a) (imag-part b)) (* (imag-part a) (real-part b))))))
  (put 'div '(complex complex)
       (lambda (a b)
         (let ((d (+ (* (real-part b) (real-part b)) (* (imag-part b) (imag-part b)))))
           (if (= d 0) (error "complex division by zero")
               (make-complex (/ (+ (* (real-part a) (real-part b)) (* (imag-part a) (imag-part b))) d)
                             (/ (- (* (imag-part a) (real-part b)) (* (real-part a) (imag-part b))) d))))))
  (put '=zero? '(complex) (lambda (z) (and (= (real-part z) 0) (= (imag-part z) 0))))
  (put 'real-part '(complex) real-part) (put 'imag-part '(complex) imag-part)
  (put 'magnitude '(complex) magnitude) (put 'angle '(complex) angle)
  (put-coercion 'rational 'scheme-number
                (lambda (x) (let ((r (contents x))) (make-scheme-number (/ (car r) (cdr r))))))
  (put-coercion 'scheme-number 'complex (lambda (x) (make-complex (contents x) 0)))
  (put-coercion 'rational 'complex
                (lambda (x) (let ((r (contents x))) (make-complex (/ (car r) (cdr r)) 0)))))
(install-numbers)
;; Sparse terms are (nonnegative-exact-order tagged-coefficient), descending.
(define make-term list)
(define order car)
(define coeff cadr)
(define (contains-variable? coefficient var)
  (and (eq? (type-tag coefficient) 'polynomial)
       (let ((p (contents coefficient)))
         (or (eq? (car p) var)
             (let loop ((terms (cdr p)))
               (and (pair? terms)
                    (or (contains-variable? (coeff (car terms)) var) (loop (cdr terms)))))))))
(define (make-polynomial var terms)
  (define (validate rest previous)
    (if (not (null? rest))
        (let ((t (car rest)))
          (if (not (and (list? t) (= (length t) 2) (integer? (order t))
                        (exact? (order t)) (>= (order t) 0)
                        (or (not previous) (< (order t) previous))))
              (error "terms must have distinct descending nonnegative orders" t))
          (=zero? (coeff t)) ; Ensures that the coefficient participates in dispatch.
          (if (contains-variable? (coeff t) var) (error "coefficient depends on polynomial variable" var))
          (validate (cdr rest) (order t)))))
  (if (not (and (symbol? var) (list? terms))) (error "invalid polynomial" var terms))
  (validate terms #f)
  (attach-tag 'polynomial (cons var terms)))
(define (adjoin-term t terms) (if (=zero? (coeff t)) terms (cons t terms)))
(define (add-terms a b)
  (cond ((null? a) b) ((null? b) a)
        (else
         (let ((x (car a)) (y (car b)))
           (cond ((> (order x) (order y)) (adjoin-term x (add-terms (cdr a) b)))
                 ((< (order x) (order y)) (adjoin-term y (add-terms a (cdr b))))
                 (else (adjoin-term (make-term (order x) (add (coeff x) (coeff y)))
                                    (add-terms (cdr a) (cdr b)))))))))
(define (mul-term-by-all t terms)
  (if (null? terms) '()
      (adjoin-term (make-term (+ (order t) (order (car terms))) (mul (coeff t) (coeff (car terms))))
                   (mul-term-by-all t (cdr terms)))))
(define (mul-terms a b)
  (if (null? a) '() (add-terms (mul-term-by-all (car a) b) (mul-terms (cdr a) b))))
(define (combine-polynomials combine a b)
  (if (not (eq? (car a) (car b))) (error "polynomial variables differ" (car a) (car b))
      (make-polynomial (car a) (combine (cdr a) (cdr b)))))
;; 2.87: all coefficients must be generically zero; empty terms are zero too.
(define (zero-terms? terms)
  (or (null? terms) (and (=zero? (coeff (car terms))) (zero-terms? (cdr terms)))))
(put '=zero? '(polynomial) (lambda (p) (zero-terms? (cdr p))))
(put 'add '(polynomial polynomial) (lambda (a b) (combine-polynomials add-terms a b)))
(put 'mul '(polynomial polynomial) (lambda (a b) (combine-polynomials mul-terms a b)))
(define (check label actual expected)
  (if (not (equal? actual expected)) (error "check failed" label actual expected)))
(define (check-error label thunk)
  (check label (with-handlers ((exn:fail? (lambda (e) #t))) (thunk) #f) #t))
(define (self-check)
  (check 'rational-add (add (make-rational 1 2) (make-rational 1 3)) (make-rational 5 6))
  (check 'rational-sub (sub (make-rational 1 2) (make-rational 1 3)) (make-rational 1 6))
  (check 'rational-div (div (make-rational 1 2) (make-rational 1 3)) (make-rational 3 2))
  (check 'mixed-rational-host (add (make-rational 1 2) (make-scheme-number 2)) (make-scheme-number 5/2))
  (check 'complex-mixed (add (make-scheme-number 2) (make-complex 3 4)) (make-complex 5 4))
  (check 'reverse-coercion (add (make-complex 3 4) (make-rational 1 2)) (make-complex 7/2 4))
  (check 'complex-mul (mul (make-complex 1 2) (make-complex 1 -2)) (make-complex 5 0))
  (check 'complex-div (div (make-complex 3 4) (make-complex 1 0)) (make-complex 3 4))
  (check 'nested-tag (magnitude (make-complex 3 4)) 5)
  (check 'polar-inner-add
         (real-part (add (attach-tag 'complex (make-from-mag-ang 2 0)) (make-complex 3 4))) 5)
  (check 'exp (generic-exp (make-scheme-number 2) (make-scheme-number 3)) (make-scheme-number 8))
  ;; Install Louis's identity conversions deliberately; fixed dispatcher never uses them.
  (put-coercion 'scheme-number 'scheme-number (lambda (x) x))
  (put-coercion 'complex 'complex (lambda (x) x))
  (check-error 'complex-exp-terminates (lambda () (generic-exp (make-complex 1 1) (make-complex 2 0))))
  (check-error 'same-type-missing (lambda () (apply-generic 'unknown (make-scheme-number 1) (make-scheme-number 2))))
  (for-each (lambda (z) (check 'generic-zero (=zero? z) #t))
            (list (make-scheme-number 0) (make-rational 0 -3) (make-complex 0 0)))
  (let* ((zero-y (make-polynomial 'y (list (make-term 3 (make-rational 0 7)))))
         (p (make-polynomial 'x (list (make-term 2 (make-rational 1 2)) (make-term 0 (make-rational 1 1)))))
         (minus-p (make-polynomial 'x (list (make-term 2 (make-rational -1 2)) (make-term 0 (make-rational -1 1)))))
         (nested-zero (make-polynomial 'x (list (make-term 5 zero-y)))))
    (check 'empty-zero (=zero? (make-polynomial 'x '())) #t)
    (check 'explicit-zero (=zero? zero-y) #t)
    (check 'nested-zero (=zero? nested-zero) #t)
    (check 'nonzero (=zero? p) #f)
    (check 'zero-prefix-nonzero-tail
           (=zero? (make-polynomial 'x (list (make-term 3 (make-rational 0 1))
                                            (make-term 0 (make-rational 1 1))))) #f)
    (check 'cancellation (=zero? (add p minus-p)) #t)
    (check 'drop-polynomial-zero (adjoin-term (make-term 7 zero-y) '()) '())
    (check 'poly-square (mul p p)
           (make-polynomial 'x (list (make-term 4 (make-rational 1 4))
                                    (make-term 2 (make-rational 1 1)) (make-term 0 (make-rational 1 1)))))
    (check-error 'different-variables (lambda () (add p zero-y)))
    (check-error 'scalar-polynomial-unsupported (lambda () (add p (make-scheme-number 1)))))
  (let* ((y (make-polynomial 'y (list (make-term 1 (make-scheme-number 1)))))
         (xy (make-polynomial 'x (list (make-term 1 y)))))
    (check 'recursive-coefficient-multiply (mul xy xy)
           (make-polynomial 'x (list (make-term 2 (make-polynomial 'y (list (make-term 2 (make-scheme-number 1)))))))))
  (let ((p (make-polynomial 'x (list (make-term 1 (make-rational 1 2)))))
        (q (make-polynomial 'x (list (make-term 1 (make-scheme-number 2))))))
    (check 'mixed-coefficients (add p q) (make-polynomial 'x (list (make-term 1 (make-scheme-number 5/2))))))
  (check-error 'rational-boundary (lambda () (make-rational 1 0)))
  (check-error 'rational-inexact (lambda () (make-rational 1.0 2)))
  (check-error 'zero-division (lambda () (div (make-rational 1 2) (make-rational 0 1))))
  (check-error 'complex-zero-division (lambda () (div (make-complex 1 2) (make-complex 0 0))))
  (check-error 'duplicate-order
               (lambda () (make-polynomial 'x (list (make-term 1 (make-scheme-number 1)) (make-term 1 (make-scheme-number 2))))))
  (check-error 'dependent-coefficient
               (lambda () (make-polynomial 'x (list (make-term 1 (make-polynomial 'x '()))))))
  (display "02.09: all checks passed") (newline))
(self-check)
