#lang sicp
;; SICP 第二版 §1.2.4–1.2.6，1.16 / 1.20 / 1.22。
;; 平方求幂、Euclid、试除、expmod 据教材改写；计数/边界/批量计时为补充。
(#%require (only racket/base with-handlers exn:fail?))
(define (natural? n) (and (integer? n) (exact? n) (>= n 0)))
(define (require-natural n)
  (if (not (natural? n)) (error "Expected exact nonnegative integer" n) #t))

;; 1.16：不变量 a*b^n = 原始底数^原始指数。
(define (fast-expt base exponent)
  (require-natural exponent)
  (define (iter a b n)
    (cond ((= n 0) a)
          ((even? n) (iter a (* b b) (/ n 2)))
          (else (iter (* a b) b (- n 1)))))
  (iter 1 base exponent))

;; 1.20：计数器只是观察工具，不影响余数的计算。
(define (gcd-applicative-report a b)
  (require-natural a) (require-natural b)
  (define count 0)
  (define (rem a b) (set! count (+ count 1)) (remainder a b))
  (define (euclid a b)
    (if (= b 0) a (euclid b (rem a b))))
  (let ((answer (euclid a b))) (list answer count)))

(define (gcd-normal-report a b)
  (require-natural a) (require-natural b)
  (define count 0)
  (define (rem a b) (set! count (+ count 1)) (remainder a b))
  ;; a、b 是不记忆化的零参数过程，每次调用都重算表达式。
  ;; 仅模拟本题 gcd 对参数的需要，不是完整正则序 Scheme 求值器。
  (define (euclid a b)
    (if (= (b) 0)
        (a)
        (euclid b (lambda () (rem (a) (b))))))
  (let ((answer (euclid (lambda () a) (lambda () b))))
    (list answer count)))

;; 返回 (最小除数 实际 remainder 次数)，所有试除仍按 2,3,4,...。
(define (divisor-report n)
  (if (not (and (natural? n) (>= n 2))) (error "Expected integer >= 2" n))
  (define (find d trials)
    (cond ((> (* d d) n) (list n trials))
          ((= (remainder n d) 0) (list d (+ trials 1)))
          (else (find (+ d 1) (+ trials 1)))))
  (find 2 0))
(define (prime? n)
  (and (natural? n) (>= n 2) (= n (car (divisor-report n)))))

;; 1.22：只显示成功的候选，避免候选日志淹没计时表。
;; runtime 在 #lang sicp 中以微秒计，数字并不保证逐微秒有效精度。
(define (timed-prime-test n)
  (let ((start (runtime)))
    (if (prime? n)
        (let ((elapsed (- (runtime) start)))
          (display n) (display " *** ") (display elapsed)
          (display " us") (newline) #t)
        #f)))
(define (search-for-primes low high)
  (require-natural low) (require-natural high)
  (define (search candidate found)
    (cond ((> candidate high) (reverse found))
          ((timed-prime-test candidate)
           (search (+ candidate 2) (cons candidate found)))
          (else (search (+ candidate 2) found))))
  ;; 本过程按题意仅搜索奇数，故 2 不在搜索结果中。
  (search (if (even? low) (+ low 1) low) '()))

;; 减少单次调用的计时量化影响；不是速度通过/失败测试。
(define (mean-prime-time n repetitions)
  (define (repeat remaining)
    (if (= remaining 0) #t
        (if (prime? n) (repeat (- remaining 1))
            (error "Benchmark expects a prime" n))))
  (prime? n) ; 一次预热
  (let ((start (runtime)))
    (repeat repetitions)
    (/ (- (runtime) start) (* 1.0 repetitions))))

;; 模幂：每层取模，避免先构造巨大的 base^exponent。
(define (expmod base exponent modulus)
  (cond ((= exponent 0) (remainder 1 modulus))
        ((even? exponent)
         (let ((half (expmod base (/ exponent 2) modulus)))
           (remainder (* half half) modulus)))
        (else (remainder (* base (expmod base (- exponent 1) modulus)) modulus))))
(define (fermat-pass? n a) (= (expmod a n n) a))
(define (fermat-probable-prime? n trials)
  (require-natural trials)
  (define (try remaining)
    (cond ((= remaining 0) #t)
          ((fermat-pass? n (+ 1 (random (- n 1)))) (try (- remaining 1)))
          (else #f)))
  (and (natural? n) (>= n 2) (try trials)))
(define (all-fermat-bases-pass? n)
  (define (iter a)
    (or (= a n) (and (fermat-pass? n a) (iter (+ a 1)))))
  (iter 1))

(define (check-equal label actual expected)
  (if (not (equal? actual expected))
      (error "Check failed" label actual expected) #t))
(define (raises? thunk)
  (with-handlers ((exn:fail? (lambda (e) #t))) (thunk) #f))
(define (self-check)
  (for-each (lambda (row)
              (check-equal row (fast-expt (car row) (cadr row)) (caddr row)))
            '((2 0 1) (0 0 1) (0 5 0) (2 10 1024)
              (-2 5 -32) (-2 6 64) (1/2 4 1/16)))
  (check-equal 'large-exponent (fast-expt 3 100) (expt 3 100))
  (check-equal 'bad-exponent (raises? (lambda () (fast-expt 2 -1))) #t)
  (check-equal 'applicative (gcd-applicative-report 206 40) '(2 4))
  (check-equal 'normal (gcd-normal-report 206 40) '(2 18))
  (check-equal 'gcd-zero (gcd-applicative-report 7 0) '(7 0))
  (check-equal 'gcd-both-zero (gcd-normal-report 0 0) '(0 0))
  (check-equal 'prime-boundaries (map prime? '(-3 0 1 2 3 4 9 25 97 561))
               '(#f #f #f #t #t #f #f #f #t #f))
  (check-equal 'prime-trials (divisor-report 1009) '(1009 30))
  (check-equal 'square-factor (divisor-report 49) '(7 6))
  (check-equal 'expmod (expmod 7 13 19) (remainder (expt 7 13) 19))
  (check-equal 'modulus-one (expmod 2 0 1) 0)
  (check-equal 'fermat-prime (fermat-probable-prime? 1009 5) #t)
  (check-equal 'fermat-witness (fermat-pass? 15 2) #f)
  (check-equal 'carmichael (all-fermat-bases-pass? 561) #t)
  (check-equal 'empty-range (search-for-primes 10 9) '())
  (check-equal 'odd-only (search-for-primes 0 2) '())
  (for-each
   (lambda (row)
     (let ((found (search-for-primes (car row) (cadr row))))
       (check-equal 'exercise-1.22 found (caddr row))
       (for-each
        (lambda (n)
          (display "batch ") (display n)
          (display ": remainder=") (display (cadr (divisor-report n)))
          (display ", mean-us=") (display (mean-prime-time n 200)) (newline))
        found)))
   '((1001 1020 (1009 1013 1019))
     (10001 10038 (10007 10009 10037))
     (100001 100044 (100003 100019 100043))
     (1000001 1000038 (1000003 1000033 1000037))))
  (display "01.04: all checks passed") (newline))
(self-check)
