#lang sicp
(#%require (only racket/base with-handlers exn:fail?))
;; Constructors adapted from SICP §2.3.2. These are algebraic data, not calls.
(define (=number? x n) (and (number? x) (= x n)))
(define (make-sum a b)
  (cond ((=number? a 0) b) ((=number? b 0) a)
        ((and (number? a) (number? b)) (+ a b)) (else (list '+ a b))))
(define (make-product a b)
  (cond ((or (=number? a 0) (=number? b 0)) 0)
        ((=number? a 1) b) ((=number? b 1) a)
        ((and (number? a) (number? b)) (* a b)) (else (list '* a b))))
(define (make-exponentiation b n)
  (cond ((=number? n 0) 1) ((=number? n 1) b)
        ((and (number? b) (number? n)) (expt b n)) (else (list '** b n))))
(define (exponentiation? e) (and (pair? e) (eq? (car e) '**)))
(define base cadr)
(define exponent caddr)
(define (constant-exponent? e var)
  (cond ((number? e) #t) ((symbol? e) (not (eq? e var)))
        (else (let ((parts (prefix-view e)))
                (and (constant-exponent? (cadr parts) var)
                     (constant-exponent? (caddr parts) var))))))
;; One rule engine; each view returns (operator left right).
(define (make-differentiator view sum product power)
  (define (deriv e var)
    (cond ((number? e) 0)
          ((symbol? e) (if (eq? e var) 1 0))
          (else
           (let* ((parts (view e)) (op (car parts)) (a (cadr parts)) (b (caddr parts)))
             (cond ((eq? op 'group) (deriv a var))
                   ((eq? op '+) (sum (deriv a var) (deriv b var)))
                   ((eq? op '*) (sum (product a (deriv b var)) (product (deriv a var) b)))
                   ((eq? op '**)
                    ;; u^0 is constant; avoid eagerly constructing 0^-1 when u=0.
                    (cond ((=number? b 0) 0)
                          ((not (constant-exponent? b var))
                           (error "power rule requires exponent independent of variable" e))
                          (else (product (product b (power a (sum b -1))) (deriv a var)))))
                   (else (error "unknown operator" op)))))))
  deriv)
(define (prefix-view e)
  (if (and (list? e) (= (length e) 3) (memq (car e) '(+ * **))) e
      (error "invalid binary prefix expression" e)))
(define deriv (make-differentiator prefix-view make-sum make-product make-exponentiation))
;; 2.58a: only fully parenthesized binary infix representation changes.
(define (binary-infix-view e)
  (if (and (list? e) (= (length e) 3) (memq (cadr e) '(+ *)))
      (list (cadr e) (car e) (caddr e)) (error "invalid binary infix" e)))
(define (infix-sum a b)
  (let ((s (make-sum a b)))
    (if (and (pair? s) (eq? (car s) '+)) (list a '+ b) s)))
(define (infix-product a b)
  (let ((p (make-product a b)))
    (if (and (pair? p) (eq? (car p) '*)) (list a '* b) p)))
(define deriv-infix-a (make-differentiator binary-infix-view infix-sum infix-product make-exponentiation))
;; 2.58b: look only at TOP LEVEL operators, split + before *.
;; ponytail: repeated scans can be quadratic; parse once to an AST for large inputs.
(define (operand? x)
  (or (number? x) (and (symbol? x) (not (memq x '(+ *))))
      (and (list? x) (not (null? x)))))
(define (valid-token-sequence? xs)
  (and (pair? xs) (operand? (car xs))
       (or (null? (cdr xs))
           (and (pair? (cdr xs)) (memq (cadr xs) '(+ *))
                (valid-token-sequence? (cddr xs))))))
(define (unpack xs) (if (null? (cdr xs)) (car xs) xs))
(define (split-at op xs)
  (define (scan rest before)
    (cond ((null? rest) #f)
          ((eq? (car rest) op) (list op (unpack (reverse before)) (unpack (cdr rest))))
          (else (scan (cdr rest) (cons (car rest) before)))))
  (scan xs '()))
(define (flat-infix-view e)
  (if (not (and (list? e) (valid-token-sequence? e))) (error "invalid infix tokens" e)
      (if (null? (cdr e)) (list 'group (car e) #f)
          (or (split-at '+ e) (split-at '* e) (error "missing infix operator" e)))))
(define deriv-infix-b (make-differentiator flat-infix-view infix-sum infix-product make-exponentiation))
(define (check label actual expected)
  (if (not (equal? actual expected)) (error "check failed" label actual expected)))
(define (check-error label thunk)
  (check label (with-handlers ((exn:fail? (lambda (e) #t))) (thunk) #f) #t))
(define (self-check)
  (check 'quote (list (car '(+ x 1)) (car ''x)) '(+ quote))
  (check 'constant (deriv 7 'x) 0)
  (check 'other-variable (deriv 'y 'x) 0)
  (check 'power (deriv '(** x 3) 'x) '(* 3 (** x 2)))
  (check 'symbolic-constant-exponent (deriv '(** x n) 'x) '(* n (** x (+ n -1))))
  (check 'compound-constant-exponent (deriv '(** x (+ y 1)) 'x)
         '(* (+ y 1) (** x (+ (+ y 1) -1))))
  (check 'chain (deriv '(** (+ x 1) 3) 'x) '(* 3 (** (+ x 1) 2)))
  (check 'nonunit-chain (deriv '(** (* 2 x) 3) 'x) '(* (* 3 (** (* 2 x) 2)) 2))
  (check 'power-zero (deriv '(** x 0) 'x) 0)
  (check 'zero-to-zero-derivative (deriv '(** 0 0) 'x) 0)
  (check 'power-one (deriv '(** x 1) 'x) 1)
  (check 'power-parts (list (exponentiation? '(** x 2)) (base '(** x 2)) (exponent '(** x 2)))
         '(#t x 2))
  (check 'infix-a (deriv-infix-a '(x + (3 * (x + (y + 2)))) 'x) 4)
  (check 'infix-b (deriv-infix-b '(x + 3 * (x + y + 2)) 'x) 4)
  (check 'precedence (deriv-infix-b '(x * x + x * 3) 'x) '((x + x) + 3))
  (check 'nested-precedence (deriv-infix-b '(x * (x + 3)) 'x) '(x + (x + 3)))
  (check 'flat-product (deriv-infix-b '(x * x * x) 'x) '((x * (x + x)) + (x * x)))
  (check 'group (deriv-infix-b '((x)) 'x) 1)
  (check-error 'variable-exponent (lambda () (deriv '(** x x) 'x)))
  (check-error 'unknown (lambda () (deriv '(sin x) 'x)))
  (check-error 'missing-operand (lambda () (deriv-infix-b '(x +) 'x)))
  (check-error 'bad-operator (lambda () (deriv-infix-b '(x - 2) 'x)))
  (check-error 'not-binary (lambda () (deriv-infix-a '(x + x + 1) 'x)))
  (display "02.06: all checks passed") (newline))
(self-check)
