#lang sicp
;; Shared only by 02.08 and 02.09. Operation table adapted from SICP §2.4.3.
(#%provide put get attach-tag type-tag contents dispatch
           make-from-real-imag make-from-mag-ang real-part imag-part magnitude angle)
;; ponytail: linear association table; use hashing only if method count warrants it.
(define table '())
(define (put op types procedure)
  (let ((key (list op types)))
    (let ((record (assoc key table)))
      (if record (set-cdr! record procedure)
          (set! table (cons (cons key procedure) table))))))
(define (get op types)
  (let ((record (assoc (list op types) table))) (if record (cdr record) #f)))
(define (attach-tag tag value) (cons tag value))
(define (type-tag datum)
  (if (and (pair? datum) (symbol? (car datum))) (car datum) (error "invalid tagged datum" datum)))
(define (contents datum) (type-tag datum) (cdr datum))
(define (dispatch op . args)
  (let ((proc (get op (map type-tag args))))
    (if proc (apply proc (map contents args)) (error "no method" op (map type-tag args)))))
(define (real-part z) (dispatch 'real-part z))
(define (imag-part z) (dispatch 'imag-part z))
(define (magnitude z) (dispatch 'magnitude z))
(define (angle z) (dispatch 'angle z))
(define (finite-real? x) (and (real? x) (< -inf.0 x +inf.0)))
(define (install-rectangular-package)
  (define (make x y)
    (if (and (finite-real? x) (finite-real? y)) (attach-tag 'rectangular (cons x y))
        (error "invalid rectangular coordinates" x y)))
  (put 'make-from-real-imag 'rectangular make)
  (put 'real-part '(rectangular) car)
  (put 'imag-part '(rectangular) cdr)
  (put 'magnitude '(rectangular) (lambda (z) (sqrt (+ (* (car z) (car z)) (* (cdr z) (cdr z))))))
  (put 'angle '(rectangular) (lambda (z) (if (and (= (car z) 0) (= (cdr z) 0)) 0 (atan (cdr z) (car z))))))
(define (install-polar-package)
  (define (make r a)
    (if (and (finite-real? r) (>= r 0) (finite-real? a)) (attach-tag 'polar (cons r a))
        (error "invalid polar coordinates" r a)))
  (put 'make-from-mag-ang 'polar make)
  (put 'magnitude '(polar) car)
  (put 'angle '(polar) cdr)
  (put 'real-part '(polar) (lambda (z) (* (car z) (cos (cdr z)))))
  (put 'imag-part '(polar) (lambda (z) (* (car z) (sin (cdr z))))))
(define (make-from-real-imag x y) ((get 'make-from-real-imag 'rectangular) x y))
(define (make-from-mag-ang r a) ((get 'make-from-mag-ang 'polar) r a))
(install-rectangular-package)
(install-polar-package)
