#lang sicp
(#%require "dispatch-core.rkt" (only racket/base with-handlers exn:fail?))
;; §2.4 upper layer need not know rectangular/polar layout.
(define (add-complex a b)
  (make-from-real-imag (+ (real-part a) (real-part b)) (+ (imag-part a) (imag-part b))))
(define (mul-complex a b)
  (make-from-mag-ang (* (magnitude a) (magnitude b)) (+ (angle a) (angle b))))
;; 2.73: operation/operator dispatch, methods receive only operands and variable.
(define (=number? x n) (and (number? x) (= x n)))
(define (make-sum a b)
  (cond ((=number? a 0) b) ((=number? b 0) a)
        ((and (number? a) (number? b)) (+ a b)) (else (list '+ a b))))
(define (make-product a b)
  (cond ((or (=number? a 0) (=number? b 0)) 0)
        ((=number? a 1) b) ((=number? b 1) a)
        ((and (number? a) (number? b)) (* a b)) (else (list '* a b))))
(define (make-power a b)
  (cond ((=number? b 0) 1) ((=number? b 1) a) (else (list '** a b))))
(define (constant-exponent? e var)
  (cond ((number? e) #t) ((symbol? e) (not (eq? e var)))
        ((and (list? e) (= (length e) 3) (memq (car e) '(+ * **)))
         (and (constant-exponent? (cadr e) var) (constant-exponent? (caddr e) var)))
        (else (error "invalid constant exponent expression" e))))
(define (operator e) (car e))
(define (operands e) (cdr e))
(define (deriv-with lookup e var)
  (cond ((number? e) 0) ((symbol? e) (if (eq? e var) 1 0))
        ((and (list? e) (= (length e) 3))
         (let ((proc (lookup (operator e))))
           (if proc (proc (operands e) var) (error "unknown derivative operator" e))))
        (else (error "invalid binary expression" e))))
(define (deriv e var) (deriv-with (lambda (op) (get 'deriv op)) e var))
(define (deriv-reversed e var) (deriv-with (lambda (op) (get op 'deriv)) e var))
(define (install-derivatives register derivative)
  (register '+ (lambda (args var)
                 (make-sum (derivative (car args) var) (derivative (cadr args) var))))
  (register '* (lambda (args var)
                 (make-sum (make-product (car args) (derivative (cadr args) var))
                           (make-product (derivative (car args) var) (cadr args)))))
  (register '** (lambda (args var)
                  (let ((b (car args)) (n (cadr args)))
                    (if (not (constant-exponent? n var)) (error "exponent must be independent of variable" n)
                        (make-product (make-product n (make-power b (make-sum n -1)))
                                      (derivative b var)))))))
;; Both index orientations are real table entries, not alternate canned answers.
(install-derivatives (lambda (op proc) (put 'deriv op proc)) deriv)
(install-derivatives (lambda (op proc) (put op 'deriv proc)) deriv-reversed)
;; 2.75: the object itself dispatches on a message, no table or type tag.
(define (make-from-mag-ang-message r a)
  (if (not (and (real? r) (< -inf.0 r +inf.0) (>= r 0)
                (real? a) (< -inf.0 a +inf.0))) (error "invalid polar coordinates" r a))
  (lambda (op)
    (cond ((eq? op 'magnitude) r) ((eq? op 'angle) a)
          ((eq? op 'real-part) (* r (cos a))) ((eq? op 'imag-part) (* r (sin a)))
          (else (error "unknown complex message" op)))))
(define (check label actual expected)
  (if (not (equal? actual expected)) (error "check failed" label actual expected)))
(define (near label actual expected) (check label (< (abs (- actual expected)) 1e-10) #t))
(define (check-error label thunk)
  (check label (with-handlers ((exn:fail? (lambda (e) #t))) (thunk) #f) #t))
(define (self-check)
  (let ((r (make-from-real-imag 3 4)) (p (make-from-mag-ang 2 0)))
    (check 'tags (list (type-tag r) (type-tag p)) '(rectangular polar))
    (near 'magnitude (magnitude r) 5)
    (near 'mixed-add-real (real-part (add-complex r p)) 5)
    (near 'mixed-add-imag (imag-part (add-complex r p)) 4)
    (near 'mixed-mul-real (real-part (mul-complex r p)) 6)
    (near 'mixed-mul-imag (imag-part (mul-complex r p)) 8))
  (for-each (lambda (d)
              (check 'number (d 7 'x) 0) (check 'variable (d 'x 'x) 1)
              (check 'sum (d '(+ x 3) 'x) 1)
              (check 'product (d '(* x y) 'x) 'y)
              (check 'exponent (d '(** (+ x 1) 3) 'x) '(* 3 (** (+ x 1) 2)))
              (check 'symbolic-exponent (d '(** x n) 'x) '(* n (** x (+ n -1))))
              (check-error 'dependent-exponent (lambda () (d '(** x x) 'x)))
              (check-error 'unknown (lambda () (d '(/ x 3) 'x))))
            (list deriv deriv-reversed))
  (let ((z (make-from-mag-ang-message 5 (atan 4 3))))
    (near 'message-real (z 'real-part) 3) (near 'message-imag (z 'imag-part) 4)
    (check 'message-mag (z 'magnitude) 5) (near 'message-angle (z 'angle) (atan 4 3))
    (check-error 'bad-message (lambda () (z 'conjugate))))
  (check-error 'missing-method (lambda () (dispatch 'conjugate (make-from-real-imag 1 2))))
  (check-error 'negative-radius (lambda () (make-from-mag-ang-message -1 0)))
  (display "02.08: all checks passed") (newline))
(self-check)
