#lang sicp
(#%require "../04-01-metacircular/evaluator.rkt")
(#%provide make-lazy-evaluator)
;; SICP §4.2.2 adaptation. Each instance selects call-by-need or call-by-name.
;; Dispatch interface is host-side; expressions passed to it are object programs.
(define (make-lazy-evaluator memoize?)
  (define env (setup))
  (define (delay-it expression environment) (list 'thunk expression environment))
  (define (force-it value)
    (cond ((tagged? value 'evaluated-thunk) (cadr value))
          ((tagged? value 'thunk)
           (let ((answer (actual-value (cadr value) (caddr value))))
             (if memoize?
                 (begin (set-car! value 'evaluated-thunk)
                        (set-car! (cdr value) answer)
                        (set-cdr! (cdr value) '()))) ; release expression/environment
             answer))
          (else value)))
  (define (actual-value expression environment) (force-it (lazy-eval expression environment)))
  (define (sequence expressions environment)
    (cond ((null? expressions) (error "Empty lazy sequence"))
          ((null? (cdr expressions)) (lazy-eval (car expressions) environment))
          (else (lazy-eval (car expressions) environment)
                (sequence (cdr expressions) environment))))
  ;; A strict-interpreter or->if expansion uses a lambda parameter as a cache;
  ;; call-by-name would re-force it. Preserve short-circuit values explicitly.
  (define (lazy-and expressions environment)
    (cond ((null? expressions) #t)
          ((null? (cdr expressions)) (lazy-eval (car expressions) environment))
          ((truth? (actual-value (car expressions) environment))
           (lazy-and (cdr expressions) environment))
          (else #f)))
  (define (lazy-or expressions environment)
    (cond ((null? expressions) #f)
          ((null? (cdr expressions)) (lazy-eval (car expressions) environment))
          (else (let ((value (actual-value (car expressions) environment)))
                  (if (truth? value) value (lazy-or (cdr expressions) environment))))))
  (define (lazy-apply procedure arguments caller)
    (cond ((tagged? procedure 'primitive)
           (primitive-apply procedure (values-left arguments caller actual-value)))
          ((tagged? procedure 'lazy-procedure)
           (sequence (caddr procedure)
                     (extend (cadr procedure)
                             (map (lambda (e) (delay-it e caller)) arguments)
                             (cadddr procedure))))
          (else (error "Not a lazy procedure" procedure))))
  (define (lazy-eval e environment)
    (cond ((literal? e) e)
          ((symbol? e) (lookup e environment))
          ((tagged? e 'quote) (cadr e))
          ((tagged? e 'if)
           (lazy-eval (if (truth? (actual-value (cadr e) environment))
                          (caddr e) (alternative e)) environment))
          ((tagged? e 'lambda) (list 'lazy-procedure (cadr e) (cddr e) environment))
          ((tagged? e 'begin) (sequence (cdr e) environment))
          ((tagged? e 'define) (define! (def-name e) (lazy-eval (def-value e) environment) environment))
          ((tagged? e 'set!) (assign! (cadr e) (lazy-eval (caddr e) environment) environment))
          ((tagged? e 'and) (lazy-and (cdr e) environment))
          ((tagged? e 'or) (lazy-or (cdr e) environment))
          ((derived? e) (lazy-eval (expand e) environment))
          ((pair? e) (lazy-apply (actual-value (car e) environment) (cdr e) environment))
          (else (error "Unknown lazy expression" e))))
  (lambda (message expression)
    (cond ((eq? message 'eval) (lazy-eval expression env))
          ((eq? message 'actual) (actual-value expression env))
          (else (error "Unknown lazy request" message)))))
