#lang sicp
(#%require "../04-01-metacircular/evaluator.rkt" "lazy-evaluator.rkt")
(define (install-id evaluator)
  (evaluator 'eval '(begin (define count 0)
                          (define (id x) (set! count (+ count 1)) x)
                          (define (square x) (* x x)))))
(define (self-check)
  (let ((need (make-lazy-evaluator #t)))
    (install-id need)
    (need 'eval '(define w (id (id 10))))
    (check 'exercise-4.27-count-before (need 'actual 'count) 1)
    (check 'exercise-4.27-w (need 'actual 'w) 10)
    (check 'exercise-4.27-count-after (need 'actual 'count) 2)
    (check 'cached-w (need 'actual 'w) 10)
    (check 'cached-count (need 'actual 'count) 2)
    (check 'unused-error (need 'actual '((lambda (x y) x) 7 (/ 1 0))) 7)
    (check 'force-operator (need 'actual '((id (lambda (x) (+ x 1))) 8)) 9)
    (check 'thunk-caller-environment
           (need 'actual '(let ((x 7))
                            (let ((f (lambda (y) (let ((x 100)) y)))) (f x)))) 7)
    (check-error 'needed-error (lambda () (need 'actual '(+ 1 (/ 1 0))))))
  (for-each
   (lambda (memo?)
     (let ((evaluator (make-lazy-evaluator memo?)))
       (install-id evaluator)
       (check 'exercise-4.29-value (evaluator 'actual '(square (id 10))) 100)
       (check 'exercise-4.29-count (evaluator 'actual 'count) (if memo? 1 2))
       (evaluator 'eval '(set! count 0))
       (check 'or-short-circuit (evaluator 'actual '(or (id 10) (/ 1 0))) 10)
       (check 'or-does-not-repeat-effect (evaluator 'actual 'count) 1)
       (check 'empty-and (evaluator 'actual '(and)) #t)
       (check 'empty-or (evaluator 'actual '(or)) #f)
       (check 'and-short-circuit (evaluator 'actual '(and #f (/ 1 0))) #f)
       (check 'and-last-value (evaluator 'actual '(and 1 2)) 2)
       (evaluator 'eval '(set! count 0))
       (evaluator 'eval '(define (twice x) (+ x x)))
       (evaluator 'eval '(define (grow n)
                           (if (= n 0) (id 1) (twice (grow (- n 1))))))
       (check 'exponential-value (evaluator 'actual '(grow 10)) 1024)
       (check 'exponential-work (evaluator 'actual 'count) (if memo? 1 1024))
       (display (list 'memoization memo? 'leaf-evaluations (evaluator 'actual 'count))) (newline)))
   '(#t #f))
  (let ((need (make-lazy-evaluator #t)))
    ;; Object-language pairs are procedures, not host mutable pairs.
    (need 'eval '(begin
                   (define (cons x y) (lambda (m) (m x y)))
                   (define (car z) (z (lambda (p q) p)))
                   (define (cdr z) (z (lambda (p q) q)))
                   (define (integers-from n) (cons n (integers-from (+ n 1))))
                   (define (list-ref xs n)
                     (if (= n 0) (car xs) (list-ref (cdr xs) (- n 1))))
                   (define integers (integers-from 1))))
    (check 'infinite-lazy-list (need 'actual '(list-ref integers 17)) 18)
    (check 'head-is-lazy (need 'actual '(car (cdr (cons (/ 1 0) (cons 8 '()))))) 8)
    (check 'tail-is-lazy (need 'actual '(car (cons 7 (/ 1 0)))) 7)
    (check-error 'quoted-host-pair (lambda () (need 'actual '(car '(a b))))))
  (display "04.03: all checks passed") (newline))
(self-check)
