#lang sicp
;; Core sequence combinators adapted from SICP §2.2.3.
(define (accumulate op initial sequence)
  (if (null? sequence) initial
      (op (car sequence) (accumulate op initial (cdr sequence)))))
(define fold-right accumulate)
(define (fold-left op initial sequence)
  (define (iter result rest)
    (if (null? rest) result (iter (op result (car rest)) (cdr rest))))
  (iter initial sequence))
;; 2.33: three missing accumulation bodies.
(define (map-acc p sequence)
  (accumulate (lambda (x y) (cons (p x) y)) '() sequence))
(define (append-acc seq1 seq2) (accumulate cons seq2 seq1))
(define (length-acc sequence) (accumulate (lambda (x y) (+ 1 y)) 0 sequence))
(define (filter-seq predicate sequence)
  (cond ((null? sequence) '())
        ((predicate (car sequence))
         (cons (car sequence) (filter-seq predicate (cdr sequence))))
        (else (filter-seq predicate (cdr sequence)))))
(define (enumerate lo hi)
  (if (> lo hi) '() (cons lo (enumerate (+ lo 1) hi))))
(define (enumerate-tree tree)
  (cond ((null? tree) '()) ((not (pair? tree)) (list tree))
        (else (append-acc (enumerate-tree (car tree)) (enumerate-tree (cdr tree))))))
(define (flatmap p seq) (accumulate append-acc '() (map-acc p seq)))
(define (unique-pairs n)
  (flatmap (lambda (i) (map-acc (lambda (j) (list i j)) (enumerate 1 (- i 1))))
           (enumerate 1 n)))
(define (prime? n)
  (define (try d)
    (cond ((> (* d d) n) #t) ((= (remainder n d) 0) #f) (else (try (+ d 1)))))
  (and (> n 1) (try 2)))
(define (prime-sum-pairs n)
  (map-acc (lambda (p) (list (car p) (cadr p) (+ (car p) (cadr p))))
           (filter-seq (lambda (p) (prime? (+ (car p) (cadr p)))) (unique-pairs n))))
(define (check label actual expected)
  (if (not (equal? actual expected)) (error "check failed" label actual expected)))
(define (self-check)
  (check 'map (map-acc (lambda (x) (* x x)) '(1 2 3)) '(1 4 9))
  (check 'append (append-acc '(1 2) '(3 4)) '(1 2 3 4))
  (check 'length (length-acc '(a (b c) d)) 3)
  (check 'empty (list (map-acc abs '()) (append-acc '() '(x)) (length-acc '()))
         '(() (x) 0))
  (check 'right-div (fold-right / 1 '(1 2 3)) 3/2)
  (check 'left-div (fold-left / 1 '(1 2 3)) 1/6)
  (check 'right-list (fold-right list '() '(1 2 3)) '(1 (2 (3 ()))))
  (check 'left-list (fold-left list '() '(1 2 3)) '(((() 1) 2) 3))
  (for-each (lambda (xs) (check xs (fold-left + 0 xs) (fold-right + 0 xs)))
            '(() (1) (1 2 3) (-1 1)))
  ;; Associative, noncommutative append agrees when initial is its identity.
  (check 'noncommutative-monoid (fold-left append-acc '() '((1) (2) (3)))
         (fold-right append-acc '() '((1) (2) (3))))
  (check 'initial-position-right (fold-right append-acc '(z) '((a) (b))) '(a b z))
  (check 'initial-position-left (fold-left append-acc '(z) '((a) (b))) '(z a b))
  (check 'pipeline (accumulate + 0 (map-acc (lambda (x) (* x x))
                   (filter-seq odd? (enumerate-tree '(1 (2 (3 4)) 5))))) 35)
  (check 'nested-mapping (prime-sum-pairs 6)
         '((2 1 3) (3 2 5) (4 1 5) (4 3 7) (5 2 7) (6 1 7) (6 5 11)))
  (check 'empty-pairs (prime-sum-pairs 0) '())
  (display "02.04: all checks passed") (newline))
(self-check)
