#lang sicp
(#%require (only racket/base with-handlers exn:fail?))
(define (last-pair items)
  (cond ((not (pair? items)) (error "last-pair needs nonempty proper list" items))
        ((null? (cdr items)) items)
        (else (last-pair (cdr items)))))
;; SICP's recursive fringe plan, with a tail argument instead of repeated append.
;; walk(t, tail) returns the leaves of t followed by tail.
(define (fringe tree)
  (define (walk t tail)
    (cond ((null? t) tail)
          ((not (pair? t)) (cons t tail))
          (else (walk (car t) (walk (cdr t) tail)))))
  (walk tree '()))
(define (count-leaves tree)
  (cond ((null? tree) 0) ((not (pair? tree)) 1)
        (else (+ (count-leaves (car tree)) (count-leaves (cdr tree))))))
(define (check label actual expected)
  (if (not (equal? actual expected)) (error "check failed" label actual expected)))
(define (check-error label thunk)
  (check label (with-handlers ((exn:fail? (lambda (e) #t))) (thunk) #f) #t))
(define (self-check)
  (check 'last (last-pair '(23 72 149 34)) '(34))
  (check 'singleton (last-pair '(x)) '(x))
  (check-error 'empty-last (lambda () (last-pair '())))
  (check-error 'improper-last (lambda () (last-pair '(1 . 2))))
  (let ((x (list (list 1 2) (list 3 4))))
    (check 'fringe (fringe x) '(1 2 3 4))
    (check 'repeated-subtree (fringe (list x x)) '(1 2 3 4 1 2 3 4))
    (check 'leaf-count (count-leaves x) 4))
  (check 'empty (fringe '()) '())
  (check 'nested-empty (fringe '(() (1 ()) (2 (3)) ())) '(1 2 3))
  (check 'pair-tree (fringe '(1 . 2)) '(1 2))
  (check 'atom (fringe 'a) '(a))
  (let* ((tail (list 3)) (xs (cons 1 (cons 2 tail))))
    (check 'last-is-shared-tail (eq? (last-pair xs) tail) #t))
  (display "02.03: all checks passed") (newline))
(self-check)
