#lang sicp
(#%require (only racket/base with-handlers exn:fail?))
;; 2.61: proper ascending numeric lists without duplicates.
(define (adjoin-set x set)
  (cond ((null? set) (list x)) ((= x (car set)) set)
        ((< x (car set)) (cons x set))
        (else (cons (car set) (adjoin-set x (cdr set))))))
(define (ordered-member? x set)
  (cond ((null? set) #f) ((= x (car set)) #t) ((< x (car set)) #f)
        (else (ordered-member? x (cdr set)))))
(define (intersection a b)
  (cond ((or (null? a) (null? b)) '())
        ((= (car a) (car b)) (cons (car a) (intersection (cdr a) (cdr b))))
        ((< (car a) (car b)) (intersection (cdr a) b))
        (else (intersection a (cdr b)))))
(define (tree-insert x t)
  (cond ((null? t) (list x '() '())) ((= x (car t)) t)
        ((< x (car t)) (list (car t) (tree-insert x (cadr t)) (caddr t)))
        (else (list (car t) (cadr t) (tree-insert x (caddr t))))))
(define (tree-member? x t)
  (cond ((null? t) #f) ((= x (car t)) #t)
        ((< x (car t)) (tree-member? x (cadr t)))
        (else (tree-member? x (caddr t)))))
;; Huffman representation and decode traversal adapted from SICP §2.3.4.
(define (make-leaf symbol weight) (list 'leaf symbol weight))
(define (leaf? t) (eq? (car t) 'leaf))
(define symbol-leaf cadr)
(define (symbols t) (if (leaf? t) (list (symbol-leaf t)) (caddr t)))
(define (weight t) (if (leaf? t) (caddr t) (cadddr t)))
(define left-branch car)
(define right-branch cadr)
(define (make-code-tree left right)
  (list left right (append (symbols left) (symbols right)) (+ (weight left) (weight right))))
(define (encode-symbol s tree)
  (define (walk t)
    (cond ((leaf? t) '())
          ((memq s (symbols (left-branch t))) (cons 0 (walk (left-branch t))))
          (else (cons 1 (walk (right-branch t))))))
  (cond ((not (memq s (symbols tree))) (error "symbol absent from Huffman alphabet" s))
        ;; Explicit singleton convention: one zero per occurrence, never empty code.
        ((leaf? tree) '(0)) (else (walk tree))))
(define (encode message tree)
  (if (null? message) '()
      (append (encode-symbol (car message) tree) (encode (cdr message) tree))))
(define (decode bits tree)
  (define (choose bit t)
    (cond ((eqv? bit 0) (left-branch t)) ((eqv? bit 1) (right-branch t))
          (else (error "invalid bit" bit))))
  (define (walk rest t)
    (cond ((null? rest) (if (eq? t tree) '() (error "truncated Huffman code")))
          (else (let ((next (choose (car rest) t)))
                  (if (leaf? next) (cons (symbol-leaf next) (walk (cdr rest) tree))
                      (walk (cdr rest) next))))))
  (if (leaf? tree)
      (map (lambda (bit) (if (eqv? bit 0) (symbol-leaf tree) (error "singleton code must be 0" bit))) bits)
      (walk bits tree)))
;; Small list-based greedy builder, ties inserted after existing equal weights.
;; ponytail: quadratic queue work; a priority queue suits large alphabets.
(define (adjoin-weighted t ts)
  (cond ((null? ts) (list t)) ((< (weight t) (weight (car ts))) (cons t ts))
        (else (cons (car ts) (adjoin-weighted t (cdr ts))))))
(define (generate-huffman-tree pairs)
  (define (leaves rest seen)
    (if (null? rest) '()
        (let ((p (car rest)))
          (if (not (and (list? p) (= (length p) 2) (symbol? (car p))
                        (real? (cadr p)) (< 0 (cadr p) +inf.0) (not (memq (car p) seen))))
              (error "invalid/duplicate frequency entry" p)
              (adjoin-weighted (make-leaf (car p) (cadr p))
                               (leaves (cdr rest) (cons (car p) seen)))))))
  (define (merge ts)
    (if (null? (cdr ts)) (car ts)
        (merge (adjoin-weighted (make-code-tree (car ts) (cadr ts)) (cddr ts)))))
  (if (null? pairs) (error "empty Huffman alphabet") (merge (leaves pairs '()))))
(define sample-tree
  (make-code-tree (make-leaf 'A 4)
    (make-code-tree (make-leaf 'B 2) (make-code-tree (make-leaf 'D 1) (make-leaf 'C 1)))))
(define sample-bits '(0 1 1 0 0 1 0 1 0 1 1 1 0))
(define (check label actual expected)
  (if (not (equal? actual expected)) (error "check failed" label actual expected)))
(define (check-error label thunk)
  (check label (with-handlers ((exn:fail? (lambda (e) #t))) (thunk) #f) #t))
(define (self-check)
  (check 'insert (adjoin-set 4 '(1 3 5)) '(1 3 4 5))
  (check 'duplicate (adjoin-set 3 '(1 3 5)) '(1 3 5))
  (check 'ends (list (adjoin-set 0 '(1 3)) (adjoin-set 4 '(1 3)) (adjoin-set 2 '()))
         '((0 1 3) (1 3 4) (2)))
  (check 'intersection (intersection '(1 3 5) '(2 3 5 7)) '(3 5))
  (check 'ordered-miss (ordered-member? 2 '(1 3 5)) #f)
  (let ((t (tree-insert 3 (tree-insert 1 (tree-insert 2 '())))))
    (check 'tree (list (tree-member? 3 t) (tree-member? 4 t)) '(#t #f)))
  (check 'decode-sample (decode sample-bits sample-tree) '(A D A B B C A))
  (check 'encode-sample (encode '(A D A B B C A) sample-tree) sample-bits)
  (check 'empty-message (decode (encode '() sample-tree) sample-tree) '())
  (check-error 'missing-symbol (lambda () (encode '(A Z) sample-tree)))
  (check-error 'invalid-bit (lambda () (decode '(2) sample-tree)))
  (check-error 'truncated (lambda () (decode '(1) sample-tree)))
  (let ((t (generate-huffman-tree '((A 4) (B 2) (C 1) (D 1)))))
    (check 'greedy-weight (weight t) 8)
    (check 'greedy-roundtrip (decode (encode '(A B C D D C B A) t) t) '(A B C D D C B A))
    (check 'weighted-cost (+ (* 4 (length (encode-symbol 'A t)))
                             (* 2 (length (encode-symbol 'B t)))
                             (length (encode-symbol 'C t)) (length (encode-symbol 'D t))) 14))
  (let ((t (generate-huffman-tree '((A 1)))))
    (check 'singleton (encode '(A A A) t) '(0 0 0))
    (check 'singleton-roundtrip (decode '(0 0 0) t) '(A A A))
    (check-error 'singleton-missing (lambda () (encode '(B) t)))
    (check-error 'singleton-invalid (lambda () (decode '(1) t))))
  (check-error 'empty-alphabet (lambda () (generate-huffman-tree '())))
  (check-error 'duplicate-alphabet (lambda () (generate-huffman-tree '((A 1) (A 2)))))
  (check-error 'zero-frequency (lambda () (generate-huffman-tree '((A 0)))))
  (display "02.07: all checks passed; sample round-trip=13 bits") (newline))
(self-check)
