#lang sicp
(#%require (only racket/base with-handlers exn:fail?))
;; Connector/primitive constraint protocol closely adapted from SICP §3.3.5.
(define (notify-except exception message constraints)
  (for-each (lambda (c) (if (not (eq? c exception)) (c message))) constraints))
(define (make-connector)
  (let ((value #f) (informant #f) (constraints '()))
    (define (set-value new setter)
      (if (eq? setter #f) (error "Informant must not be false"))
      (cond ((not informant)
             (set! value new) (set! informant setter)
             (notify-except setter 'I-have-a-value constraints))
            ((not (= value new)) (error "Contradiction" value new))
            (else 'ignored)))
    (define (forget retractor)
      (if (and informant (eq? informant retractor))
          (begin (set! informant #f)
                 (notify-except retractor 'I-lost-my-value constraints))
          'ignored))
    (define (connect-one c)
      (if (not (memq c constraints)) (set! constraints (cons c constraints)))
      (if informant (c 'I-have-a-value)) 'done)
    (lambda (m)
      (cond ((eq? m 'has-value?) (if informant #t #f))
            ((eq? m 'value) (if informant value (error "No connector value")))
            ((eq? m 'set!) set-value)
            ((eq? m 'forget!) forget)
            ((eq? m 'connect) connect-one)
            (else (error "Unknown connector request" m))))))
(define (has-value? c) (c 'has-value?))
(define (get-value c) (c 'value))
(define (set-value! c value source) ((c 'set!) value source))
(define (forget-value! c source) ((c 'forget!) source))
(define (connect c constraint) ((c 'connect) constraint))
(define (adder a b sum)
  (define (new-value)
    (cond ((and (has-value? a) (has-value? b))
           (set-value! sum (+ (get-value a) (get-value b)) me))
          ((and (has-value? a) (has-value? sum))
           (set-value! b (- (get-value sum) (get-value a)) me))
          ((and (has-value? b) (has-value? sum))
           (set-value! a (- (get-value sum) (get-value b)) me))))
  (define (me request)
    (cond ((eq? request 'I-have-a-value) (new-value))
          ((eq? request 'I-lost-my-value)
           (forget-value! a me) (forget-value! b me) (forget-value! sum me)
           (new-value))
          (else (error "Unknown adder request" request))))
  (connect a me) (connect b me) (connect sum me) me)
(define (multiplier a b product)
  (define (new-value)
    (cond ((or (and (has-value? a) (= (get-value a) 0))
               (and (has-value? b) (= (get-value b) 0)))
           (set-value! product 0 me))
          ((and (has-value? a) (has-value? b))
           (set-value! product (* (get-value a) (get-value b)) me))
          ((and (has-value? a) (has-value? product))
           (set-value! b (/ (get-value product) (get-value a)) me))
          ((and (has-value? b) (has-value? product))
           (set-value! a (/ (get-value product) (get-value b)) me))))
  (define (me request)
    (cond ((eq? request 'I-have-a-value) (new-value))
          ((eq? request 'I-lost-my-value)
           (forget-value! a me) (forget-value! b me) (forget-value! product me)
           (new-value))
          (else (error "Unknown multiplier request" request))))
  (connect a me) (connect b me) (connect product me) me)
(define (constant value connector)
  (define (me request)
    (cond ((eq? request 'I-have-a-value)
           (if (not (= value (get-value connector))) (error "Constant contradiction")))
          ((eq? request 'I-lost-my-value) (set-value! connector value me))
          (else (error "Unknown constant request" request))))
  (connect connector me) (set-value! connector value me) me)
;; 3.33: a+b = 2*c, composed only from the requested primitives.
(define (averager a b c)
  (let ((sum (make-connector)) (two (make-connector)))
    (adder a b sum) (multiplier c two sum) (constant 2 two) 'ok))
;; 3.35: reverse direction chooses the principal (nonnegative) root.
(define (squarer a b)
  (define (new-value)
    (if (has-value? b)
        (if (< (get-value b) 0)
            (error "Square less than zero" (get-value b))
            (set-value! a (sqrt (get-value b)) me))
        (if (has-value? a) (set-value! b (* (get-value a) (get-value a)) me))))
  (define (me request)
    (cond ((eq? request 'I-have-a-value) (new-value))
          ((eq? request 'I-lost-my-value)
           (forget-value! a me) (forget-value! b me) (new-value))
          (else (error "Unknown squarer request" request))))
  (connect a me) (connect b me) me)
(define (celsius-fahrenheit-converter c f)
  (let ((u (make-connector)) (v (make-connector))
        (w (make-connector)) (x (make-connector)) (y (make-connector)))
    (multiplier c w u) (multiplier v x u) (adder v y f)
    (constant 9 w) (constant 5 x) (constant 32 y) 'ok))
(define (check label actual expected)
  (if (not (equal? actual expected)) (error "Check failed" label actual expected)))
(define (raises? thunk)
  (with-handlers ((exn:fail? (lambda (e) #t))) (thunk) #f))
(define (self-check)
  (let ((a (make-connector)) (b (make-connector)) (c (make-connector)))
    (averager a b c)
    (set-value! a 10 'user) (set-value! b 20 'user)
    (check '3.33-forward (get-value c) 15)
    (forget-value! a 'stranger)
    (check 'wrong-retractor (get-value a) 10)
    (forget-value! a 'user)
    (check 'dependent-retracted (has-value? c) #f)
    (check 'independent-retained (get-value b) 20)
    (set-value! c 25 'user)
    (check '3.33-reverse (get-value a) 30)
    (check 'contradiction (raises? (lambda () (set-value! a 31 'other))) #t)
    (check 'old-value-retained (get-value a) 30))
  (let ((a (make-connector)) (b (make-connector)))
    (squarer a b) (set-value! a -3 'user)
    (check '3.35-forward (get-value b) 9)
    (forget-value! a 'user)
    (check 'square-forgotten (has-value? b) #f)
    (set-value! b 16 'user)
    (check '3.35-reverse (= (get-value a) 4) #t)
    (forget-value! b 'user)
    (set-value! b 0 'user)
    (check 'zero-root (= (get-value a) 0) #t)
    (forget-value! b 'user)
    (check 'negative-square (raises? (lambda () (set-value! b -1 'user))) #t)
    ;; Propagation errors are not transactions: explicitly retract the bad input.
    (forget-value! b 'user)
    (check 'unknown-read (raises? (lambda () (get-value b))) #t))
  (let ((a (make-connector)) (b (make-connector)) (p (make-connector)))
    (multiplier a b p) (set-value! a 0 'user)
    (check 'zero-product (get-value p) 0)
    (check 'zero-not-invertible (has-value? b) #f))
  (let ((c (make-connector)) (f (make-connector)))
    (celsius-fahrenheit-converter c f)
    (set-value! c 25 'user) (check 'c-to-f (get-value f) 77)
    (forget-value! c 'user) (check 'f-retracted (has-value? f) #f)
    (set-value! f 212 'user) (check 'f-to-c (get-value c) 100))
  (display "03.05: all checks passed") (newline))
(self-check)
