#lang sicp
;; Educational adaptation of SICP 2e §4.1; see README for source and scope.
(#%require (only racket/base gensym with-handlers exn:fail?))
(#%provide (all-defined))

(define (check label actual expected)
  (if (not (equal? actual expected))
      (error "Check failed" label actual expected) #t))
(define (check-error label action)
  (check label (with-handlers ((exn:fail? (lambda (e) 'caught)))
                 (action) 'not-caught) 'caught))
(define (tagged? x tag) (and (pair? x) (eq? (car x) tag)))
(define (literal? x) (or (number? x) (string? x) (boolean? x)))
(define (truth? x) (not (eq? x #f)))
(define (def-name e) (if (symbol? (cadr e)) (cadr e) (caadr e)))
(define (def-value e)
  (if (symbol? (cadr e)) (caddr e)
      (cons 'lambda (cons (cdadr e) (cddr e)))))
(define (alternative e) (if (null? (cdddr e)) #f (cadddr e)))

;; A frame is a mutable header holding an association list of mutable cells.
;; Extending makes new cells; set! changes a shared cell, not the outer chain.
(define (extend names values base)
  (if (not (= (length names) (length values))) (error "Arity mismatch" names values))
  (if (not (= (length names) (length (unique names)))) (error "Duplicate parameters" names))
  (cons (cons 'frame (map cons names values)) base))
(define (unique xs)
  (cond ((null? xs) '()) ((memq (car xs) (cdr xs)) (unique (cdr xs)))
        (else (cons (car xs) (unique (cdr xs))))))
(define (binding name env)
  (if (null? env) (error "Unbound variable" name)
      (let ((cell (assq name (cdar env))))
        (if cell cell (binding name (cdr env))))))
(define (lookup name env)
  (let ((v (cdr (binding name env))))
    (if (eq? v '*unassigned*) (error "Unassigned variable" name) v)))
(define (assign! name value env) (set-cdr! (binding name env) value) 'ok)
(define (define! name value env)
  (let ((cell (assq name (cdar env))))
    (if cell (set-cdr! cell value)
        (set-cdr! (car env) (cons (cons name value) (cdar env)))))
  'ok)
(define primitives
  (list (cons '+ +) (cons '- -) (cons '* *) (cons '/ /)
        (cons '= =) (cons '< <) (cons '> >) (cons '<= <=) (cons '>= >=)
        (cons 'not not) (cons 'eq? eq?) (cons 'equal? equal?)
        (cons 'cons cons) (cons 'car car) (cons 'cdr cdr)
        (cons 'cadr cadr) (cons 'caddr caddr) (cons 'list list)
        (cons 'null? null?) (cons 'pair? pair?) (cons 'member member)
        (cons 'abs abs) (cons 'remainder remainder) (cons 'integer? integer?)
        (cons 'error error)))
(define (setup)
  (let ((env (extend '() '() '())))
    (for-each (lambda (p) (define! (car p) (list 'primitive (cdr p)) env)) primitives)
    (define! 'true #t env) (define! 'false #f env) env))
(define (primitive-apply p args) (apply (cadr p) args)) ; host apply, never host eval

;; 4.1: both return values in SOURCE order, despite different effect order.
(define (values-left expressions env evaluator)
  (if (null? expressions) '()
      (let ((first (evaluator (car expressions) env)))
        (cons first (values-left (cdr expressions) env evaluator)))))
(define (values-right expressions env evaluator)
  (if (null? expressions) '()
      (let ((rest (values-right (cdr expressions) env evaluator)))
        (let ((first (evaluator (car expressions) env))) (cons first rest)))))

;; 4.4: or must neither duplicate evaluation nor capture a user variable.
(define (and->if expressions)
  (cond ((null? expressions) #t)
        ((null? (cdr expressions)) (car expressions))
        (else (list 'if (car expressions) (and->if (cdr expressions)) #f))))
(define (or->if expressions)
  (cond ((null? expressions) #f)
        ((null? (cdr expressions)) (car expressions))
        (else
         (let ((temp (gensym 'or-value)))
           (list (list 'lambda (list temp)
                       (list 'if temp temp (or->if (cdr expressions))))
                 (car expressions))))))
(define (let->application e)
  (cons (cons 'lambda (cons (map car (cadr e)) (cddr e)))
        (map cadr (cadr e))))
(define (cond->if clauses)
  (if (null? clauses) #f
      (let ((c (car clauses)))
        (if (eq? (car c) 'else)
            (if (null? (cdr clauses)) (cons 'begin (cdr c))
                (error "else must be last" clauses))
            (list 'if (car c) (cons 'begin (cdr c)) (cond->if (cdr clauses)))))))
(define (derived? e)
  (and (pair? e) (memq (car e) '(and or let cond))))
(define (expand e)
  (cond ((tagged? e 'and) (and->if (cdr e)))
        ((tagged? e 'or) (or->if (cdr e)))
        ((tagged? e 'let) (let->application e))
        ((tagged? e 'cond) (cond->if (cdr e)))
        (else (error "Not derived syntax" e))))

;; 4.16: lift immediate body definitions, preserving initializer order.
;; No descent into nested lambda/quote: those have their own scope/data.
(define (scan-out-defines body)
  (define (scan rest defs expressions)
    (if (null? rest)
        (if (null? defs) body
            (let ((ordered (reverse defs)))
              (list
               (cons 'let
                     (cons (map (lambda (d) (list (def-name d) ''*unassigned*)) ordered)
                           (append (map (lambda (d) (list 'set! (def-name d) (def-value d))) ordered)
                                   (reverse expressions)))))))
        (if (tagged? (car rest) 'define)
            (scan (cdr rest) (cons (car rest) defs) expressions)
            (scan (cdr rest) defs (cons (car rest) expressions)))))
  (scan body '() '()))
(define (make-procedure parameters body env)
  (list 'compound parameters (scan-out-defines body) env))
(define (eval-sequence expressions env)
  (cond ((null? expressions) (error "Empty sequence"))
        ((null? (cdr expressions)) (mc-eval (car expressions) env))
        (else (mc-eval (car expressions) env) (eval-sequence (cdr expressions) env))))
(define (mc-apply p args)
  (cond ((tagged? p 'primitive) (primitive-apply p args))
        ((tagged? p 'compound)
         (eval-sequence (caddr p) (extend (cadr p) args (cadddr p))))
        (else (error "Not a procedure" p))))
(define (mc-eval e env)
  (cond ((literal? e) e)
        ((symbol? e) (lookup e env))
        ((tagged? e 'quote) (cadr e))
        ((tagged? e 'if) (mc-eval (if (truth? (mc-eval (cadr e) env))
                                     (caddr e) (alternative e)) env))
        ((tagged? e 'lambda) (make-procedure (cadr e) (cddr e) env))
        ((tagged? e 'begin) (eval-sequence (cdr e) env))
        ((tagged? e 'define) (define! (def-name e) (mc-eval (def-value e) env) env))
        ((tagged? e 'set!) (assign! (cadr e) (mc-eval (caddr e) env) env))
        ((derived? e) (mc-eval (expand e) env))
        ((pair? e)
         (let ((p (mc-eval (car e) env)))
           (mc-apply p (values-left (cdr e) env mc-eval))))
        (else (error "Unknown expression" e))))
