#lang sicp
(#%require "evaluator.rkt")
(define env (setup))
(define operands '((begin (set! n (+ n 1)) n) (begin (set! n (+ n 1)) n)))
(define (self-check)
  (check 'definition (mc-eval '(define (make-adder x) (lambda (y) (+ x y))) env) 'ok)
  (check 'lexical (mc-eval '(let ((add5 (make-adder 5))) (let ((x 100)) (add5 3))) env) 8)
  (check 'operator (mc-eval '((if #t + *) 3 4) env) 7)
  (check 'quote (mc-eval '(quote (+ 1 2)) env) '(+ 1 2))
  (check 'cond (mc-eval '(cond ((= 1 2) 9) (else 8)) env) 8)
  (mc-eval '(define n 0) env)
  (check 'exercise-4.1-left (values-left operands env mc-eval) '(1 2))
  (mc-eval '(set! n 0) env)
  (check 'exercise-4.1-right (values-right operands env mc-eval) '(2 1))
  (for-each (lambda (case) (check 'exercise-4.4 (mc-eval (car case) env) (cadr case)))
            '(((and) #t) ((or) #f) ((and 1 2) 2) ((or #f 0 3) 0)
              ((and #f (/ 1 0)) #f) ((or 7 (/ 1 0)) 7)
              ((and '() 9) 9)))
  (mc-eval '(set! n 0) env)
  (check 'or-once (mc-eval '(or (begin (set! n (+ n 1)) n) 99) env) 1)
  (check 'or-effects (lookup 'n env) 1)
  (check 'no-capture (mc-eval '(let ((or-value 17)) (or #f or-value)) env) 17)
  (check 'shared-cell
         (mc-eval '(let ((x 0)) (let ((inc (lambda () (set! x (+ x 1)) x)))
                                 (list (inc) (inc)))) env) '(1 2))
  (check-error 'unbound (lambda () (mc-eval 'missing env)))
  (check-error 'arity (lambda () (mc-eval '((lambda (x) x) 1 2) env)))
  (check-error 'not-procedure (lambda () (mc-eval '(1 2) env)))
  (check-error 'bad-else (lambda () (mc-eval '(cond (else 1) (#t 2)) env)))
  (display "04.01: all checks passed") (newline)
)
(self-check)
